// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Detailed channel state info.
class ChannelStateInfo {
  final String channelId;
  final String status;
  final BigInt sequence;
  final int leafCount;
  final BigInt userBalance;
  final BigInt totalDeposited;

  const ChannelStateInfo({
    required this.channelId,
    required this.status,
    required this.sequence,
    required this.leafCount,
    required this.userBalance,
    required this.totalDeposited,
  });

  @override
  int get hashCode =>
      channelId.hashCode ^
      status.hashCode ^
      sequence.hashCode ^
      leafCount.hashCode ^
      userBalance.hashCode ^
      totalDeposited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelStateInfo &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          status == other.status &&
          sequence == other.sequence &&
          leafCount == other.leafCount &&
          userBalance == other.userBalance &&
          totalDeposited == other.totalDeposited;
}

/// Result of opening a channel.
class OpenChannelResult {
  final String channelId;
  final BigInt sequence;
  final String currentRoot;

  const OpenChannelResult({
    required this.channelId,
    required this.sequence,
    required this.currentRoot,
  });

  @override
  int get hashCode =>
      channelId.hashCode ^ sequence.hashCode ^ currentRoot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenChannelResult &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          sequence == other.sequence &&
          currentRoot == other.currentRoot;
}

/// Result of parsing a payment QR code.
class PaymentQrData {
  final String merchantDid;
  final BigInt amount;
  final String description;
  final String orderId;
  final String hubEndpoint;
  final PlatformInt64 timestamp;
  final String merchantMbPubkey;
  final String merchantMediatorUrl;

  const PaymentQrData({
    required this.merchantDid,
    required this.amount,
    required this.description,
    required this.orderId,
    required this.hubEndpoint,
    required this.timestamp,
    required this.merchantMbPubkey,
    required this.merchantMediatorUrl,
  });

  @override
  int get hashCode =>
      merchantDid.hashCode ^
      amount.hashCode ^
      description.hashCode ^
      orderId.hashCode ^
      hubEndpoint.hashCode ^
      timestamp.hashCode ^
      merchantMbPubkey.hashCode ^
      merchantMediatorUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentQrData &&
          runtimeType == other.runtimeType &&
          merchantDid == other.merchantDid &&
          amount == other.amount &&
          description == other.description &&
          orderId == other.orderId &&
          hubEndpoint == other.hubEndpoint &&
          timestamp == other.timestamp &&
          merchantMbPubkey == other.merchantMbPubkey &&
          merchantMediatorUrl == other.merchantMediatorUrl;
}

/// Result of a channel payment.
class PaymentResult {
  final String channelId;
  final BigInt sequence;
  final int leafIndex;
  final String newRoot;

  const PaymentResult({
    required this.channelId,
    required this.sequence,
    required this.leafIndex,
    required this.newRoot,
  });

  @override
  int get hashCode =>
      channelId.hashCode ^
      sequence.hashCode ^
      leafIndex.hashCode ^
      newRoot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentResult &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          sequence == other.sequence &&
          leafIndex == other.leafIndex &&
          newRoot == other.newRoot;
}
