// Copyright (c) 2026 zouyc zouyccq@gmail.com.
// All rights reserved.
//
// Licensed under the Business Source License 1.1 (BSL 1.1).
// You may not use this file except in compliance with the License.
//
// Change Date: 2031-01-01
// On the Change Date, or the fourth anniversary of the first publicly available
// distribution of the code under the BSL, whichever comes first, the code
// automatically becomes available under the Apache License 2.0.

// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Persistent channel info stored in sled.
class ChannelInfo {
  final String channelId;
  final String hubEndpoint;
  final String userPubkey;
  final String providerPubkey;
  final String status;
  final BigInt sequence;
  final BigInt balance;
  final BigInt totalDeposited;
  final int treeDepth;

  const ChannelInfo({
    required this.channelId,
    required this.hubEndpoint,
    required this.userPubkey,
    required this.providerPubkey,
    required this.status,
    required this.sequence,
    required this.balance,
    required this.totalDeposited,
    required this.treeDepth,
  });

  @override
  int get hashCode =>
      channelId.hashCode ^
      hubEndpoint.hashCode ^
      userPubkey.hashCode ^
      providerPubkey.hashCode ^
      status.hashCode ^
      sequence.hashCode ^
      balance.hashCode ^
      totalDeposited.hashCode ^
      treeDepth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelInfo &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          hubEndpoint == other.hubEndpoint &&
          userPubkey == other.userPubkey &&
          providerPubkey == other.providerPubkey &&
          status == other.status &&
          sequence == other.sequence &&
          balance == other.balance &&
          totalDeposited == other.totalDeposited &&
          treeDepth == other.treeDepth;
}
