// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Result of signing an MB voucher.
class MbVoucherResult {
  final String channelId;
  final BigInt seq;
  final BigInt amount;
  final String buyerPubkey;
  final String buyerSig;

  const MbVoucherResult({
    required this.channelId,
    required this.seq,
    required this.amount,
    required this.buyerPubkey,
    required this.buyerSig,
  });

  @override
  int get hashCode =>
      channelId.hashCode ^
      seq.hashCode ^
      amount.hashCode ^
      buyerPubkey.hashCode ^
      buyerSig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MbVoucherResult &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          seq == other.seq &&
          amount == other.amount &&
          buyerPubkey == other.buyerPubkey &&
          buyerSig == other.buyerSig;
}
