// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// A decrypted DIDComm message exposed to Flutter.
class DecryptedMessage {
  /// Message type URI (e.g. "https://didcomm.org/ignite-pay/1.0/payment-auth-request")
  final String msgType;

  /// Payment ID for authorization flows.
  final String? paymentId;

  /// DID of the merchant requesting payment.
  final String? merchantDid;

  /// Amount in lamports.
  final BigInt? amount;

  /// Human-readable description of the payment.
  final String? description;

  /// IPFS CID for list sync notifications.
  final String? listCid;

  /// Action type for list sync (add/remove).
  final String? action;

  /// Target DID for list operations.
  final String? targetDid;

  /// Raw message body as JSON string.
  final String rawBody;

  /// List type from list-sync-notification ("whitelist" or "blacklist").
  final String? listType;

  /// User-assigned label for the merchant.
  final String? label;

  const DecryptedMessage({
    required this.msgType,
    this.paymentId,
    this.merchantDid,
    this.amount,
    this.description,
    this.listCid,
    this.action,
    this.targetDid,
    required this.rawBody,
    this.listType,
    this.label,
  });

  @override
  int get hashCode =>
      msgType.hashCode ^
      paymentId.hashCode ^
      merchantDid.hashCode ^
      amount.hashCode ^
      description.hashCode ^
      listCid.hashCode ^
      action.hashCode ^
      targetDid.hashCode ^
      rawBody.hashCode ^
      listType.hashCode ^
      label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecryptedMessage &&
          runtimeType == other.runtimeType &&
          msgType == other.msgType &&
          paymentId == other.paymentId &&
          merchantDid == other.merchantDid &&
          amount == other.amount &&
          description == other.description &&
          listCid == other.listCid &&
          action == other.action &&
          targetDid == other.targetDid &&
          rawBody == other.rawBody &&
          listType == other.listType &&
          label == other.label;
}

/// A DIDComm message envelope (before decryption).
class DidcommMessage {
  /// Unique message ID.
  final String msgId;

  /// JWE encrypted envelope.
  final String jweEnvelope;

  /// Unix timestamp when the message was created.
  final PlatformInt64 createdAt;

  const DidcommMessage({
    required this.msgId,
    required this.jweEnvelope,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      msgId.hashCode ^ jweEnvelope.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DidcommMessage &&
          runtimeType == other.runtimeType &&
          msgId == other.msgId &&
          jweEnvelope == other.jweEnvelope &&
          createdAt == other.createdAt;
}
