// Copyright (c) 2026 zouyc zouyccq@gmail.com.
// All rights reserved.
//
// Licensed under the Business Source License 1.1 (BSL 1.1).
// You may not use this file except in compliance with the License.
//
// Change Date: 2031-01-01
// On the Change Date, or the fourth anniversary of the first publicly available
// distribution of the code under the BSL, whichever comes first, the code
// automatically becomes available under the Apache License 2.0.

// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// A decrypted DIDComm message exposed to Flutter.
class DecryptedMessage {
  /// Message type URI (e.g. "https://didcomm.org/ignite-pay/1.0/payment-auth-request")
  final String msgType;

  /// Payment ID for authorization flows.
  final String? paymentId;

  /// DID of the merchant requesting payment.
  final String? merchantDid;

  /// Amount in lamports.
  final BigInt? amount;

  /// Human-readable description of the payment.
  final String? description;

  /// IPFS CID for list sync notifications.
  final String? listCid;

  /// Action type for list sync (add/remove).
  final String? action;

  /// Target DID for list operations.
  final String? targetDid;

  /// Raw message body as JSON string.
  final String rawBody;

  /// List type from list-sync-notification ("whitelist" or "blacklist").
  final String? listType;

  /// User-assigned label for the merchant.
  final String? label;

  /// Base58-encoded ephemeral public key from MCP.
  final String? newSessionKeyPubkey;

  /// Base58-encoded 64-byte ephemeral keypair (secret key) from MCP.
  final String? newSessionKeySecretKey;

  /// Spending limit in lamports.
  final BigInt? newSessionKeySpendingLimit;

  /// Session duration in seconds.
  final PlatformInt64? newSessionKeyDurationSecs;

  /// Permission scopes.
  final List<String>? newSessionKeyScopes;

  /// SPL Token mint address (base58).
  final String? newSessionKeyTokenMint;

  /// Suggested SOL funding amount (lamports).
  final BigInt? newSessionKeySuggestedSolFunding;

  /// Suggested token funding amount.
  final BigInt? newSessionKeySuggestedTokenFunding;

  /// Available payment methods (e.g., ["session_key", "magicblock"]).
  final List<String>? availablePaymentMethods;
  final BigInt? sessionFundRequiredAmount;
  final BigInt? sessionFundCurrentBalance;
  final BigInt? sessionFundSpendingLimitRemaining;
  final String? sessionFundTokenMint;
  final String? sessionFundReason;
  final BigInt? balanceNotificationBalance;
  final BigInt? balanceNotificationThreshold;
  final BigInt? balanceNotificationSpendingLimitRemaining;
  final String? oldSessionKeyPubkey;
  final PlatformInt64? sessionRenewExpiresAt;
  final String? relayerPubkey;
  final String? relayerUrl;

  const DecryptedMessage({
    required this.msgType,
    this.paymentId,
    this.merchantDid,
    this.amount,
    this.description,
    this.listCid,
    this.action,
    this.targetDid,
    required this.rawBody,
    this.listType,
    this.label,
    this.newSessionKeyPubkey,
    this.newSessionKeySecretKey,
    this.newSessionKeySpendingLimit,
    this.newSessionKeyDurationSecs,
    this.newSessionKeyScopes,
    this.newSessionKeyTokenMint,
    this.newSessionKeySuggestedSolFunding,
    this.newSessionKeySuggestedTokenFunding,
    this.availablePaymentMethods,
    this.sessionFundRequiredAmount,
    this.sessionFundCurrentBalance,
    this.sessionFundSpendingLimitRemaining,
    this.sessionFundTokenMint,
    this.sessionFundReason,
    this.balanceNotificationBalance,
    this.balanceNotificationThreshold,
    this.balanceNotificationSpendingLimitRemaining,
    this.oldSessionKeyPubkey,
    this.sessionRenewExpiresAt,
    this.relayerPubkey,
    this.relayerUrl,
  });

  @override
  int get hashCode =>
      msgType.hashCode ^
      paymentId.hashCode ^
      merchantDid.hashCode ^
      amount.hashCode ^
      description.hashCode ^
      listCid.hashCode ^
      action.hashCode ^
      targetDid.hashCode ^
      rawBody.hashCode ^
      listType.hashCode ^
      label.hashCode ^
      newSessionKeyPubkey.hashCode ^
      newSessionKeySecretKey.hashCode ^
      newSessionKeySpendingLimit.hashCode ^
      newSessionKeyDurationSecs.hashCode ^
      newSessionKeyScopes.hashCode ^
      newSessionKeyTokenMint.hashCode ^
      newSessionKeySuggestedSolFunding.hashCode ^
      newSessionKeySuggestedTokenFunding.hashCode ^
      availablePaymentMethods.hashCode ^
      sessionFundRequiredAmount.hashCode ^
      sessionFundCurrentBalance.hashCode ^
      sessionFundSpendingLimitRemaining.hashCode ^
      sessionFundTokenMint.hashCode ^
      sessionFundReason.hashCode ^
      balanceNotificationBalance.hashCode ^
      balanceNotificationThreshold.hashCode ^
      balanceNotificationSpendingLimitRemaining.hashCode ^
      oldSessionKeyPubkey.hashCode ^
      sessionRenewExpiresAt.hashCode ^
      relayerPubkey.hashCode ^
      relayerUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecryptedMessage &&
          runtimeType == other.runtimeType &&
          msgType == other.msgType &&
          paymentId == other.paymentId &&
          merchantDid == other.merchantDid &&
          amount == other.amount &&
          description == other.description &&
          listCid == other.listCid &&
          action == other.action &&
          targetDid == other.targetDid &&
          rawBody == other.rawBody &&
          listType == other.listType &&
          label == other.label &&
          newSessionKeyPubkey == other.newSessionKeyPubkey &&
          newSessionKeySecretKey == other.newSessionKeySecretKey &&
          newSessionKeySpendingLimit == other.newSessionKeySpendingLimit &&
          newSessionKeyDurationSecs == other.newSessionKeyDurationSecs &&
          newSessionKeyScopes == other.newSessionKeyScopes &&
          newSessionKeyTokenMint == other.newSessionKeyTokenMint &&
          newSessionKeySuggestedSolFunding ==
              other.newSessionKeySuggestedSolFunding &&
          newSessionKeySuggestedTokenFunding ==
              other.newSessionKeySuggestedTokenFunding &&
          availablePaymentMethods == other.availablePaymentMethods &&
          sessionFundRequiredAmount == other.sessionFundRequiredAmount &&
          sessionFundCurrentBalance == other.sessionFundCurrentBalance &&
          sessionFundSpendingLimitRemaining ==
              other.sessionFundSpendingLimitRemaining &&
          sessionFundTokenMint == other.sessionFundTokenMint &&
          sessionFundReason == other.sessionFundReason &&
          balanceNotificationBalance == other.balanceNotificationBalance &&
          balanceNotificationThreshold == other.balanceNotificationThreshold &&
          balanceNotificationSpendingLimitRemaining ==
              other.balanceNotificationSpendingLimitRemaining &&
          oldSessionKeyPubkey == other.oldSessionKeyPubkey &&
          sessionRenewExpiresAt == other.sessionRenewExpiresAt &&
          relayerPubkey == other.relayerPubkey &&
          relayerUrl == other.relayerUrl;
}

/// A DIDComm message envelope (before decryption).
class DidcommMessage {
  /// Unique message ID.
  final String msgId;

  /// JWE encrypted envelope.
  final String jweEnvelope;

  /// Unix timestamp when the message was created.
  final PlatformInt64 createdAt;

  const DidcommMessage({
    required this.msgId,
    required this.jweEnvelope,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      msgId.hashCode ^ jweEnvelope.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DidcommMessage &&
          runtimeType == other.runtimeType &&
          msgId == other.msgId &&
          jweEnvelope == other.jweEnvelope &&
          createdAt == other.createdAt;
}
