// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// A decrypted DIDComm message exposed to Flutter.
class DecryptedMessage {
  /// Message type URI (e.g. "https://didcomm.org/ignite-pay/1.0/payment-auth-request")
  final String msgType;

  /// Payment ID for authorization flows.
  final String? paymentId;

  /// DID of the merchant requesting payment.
  final String? merchantDid;

  /// Amount in lamports.
  final BigInt? amount;

  /// Human-readable description of the payment.
  final String? description;

  /// IPFS CID for list sync notifications.
  final String? listCid;

  /// Action type for list sync (add/remove).
  final String? action;

  /// Target DID for list operations.
  final String? targetDid;

  /// Raw message body as JSON string.
  final String rawBody;

  /// List type from list-sync-notification ("whitelist" or "blacklist").
  final String? listType;

  /// User-assigned label for the merchant.
  final String? label;

  /// F2: MCP-provided ephemeral public key for session key registration.
  final String? newSessionKeyPubkey;

  /// F2: MCP-provided ephemeral secret key (64-byte keypair, base58) for session key registration.
  final String? newSessionKeySecretKey;

  /// F2: Spending limit in lamports for the MCP-provided session key.
  final BigInt? newSessionKeySpendingLimit;

  /// F2: Session duration in seconds for the MCP-provided session key.
  final PlatformInt64? newSessionKeyDurationSecs;

  /// F2: Permission scopes for the MCP-provided session key.
  final List<String>? newSessionKeyScopes;

  /// F2: SPL Token mint address (base58).
  final String? newSessionKeyTokenMint;

  /// F2: Suggested SOL funding amount (lamports).
  final BigInt? newSessionKeySuggestedSolFunding;

  /// F2: Suggested token funding amount.
  final BigInt? newSessionKeySuggestedTokenFunding;

  /// F2: Available payment methods (e.g., ["session_key", "magicblock"]).
  final List<String>? availablePaymentMethods;

  /// F3/F7: Required funding amount for session key.
  final BigInt? sessionFundRequiredAmount;

  /// F3/F7: Current balance of the session key.
  final BigInt? sessionFundCurrentBalance;

  /// F3/F7: Remaining spending limit.
  final BigInt? sessionFundSpendingLimitRemaining;

  /// F3/F7: Token mint address.
  final String? sessionFundTokenMint;

  /// F3/F7: Reason for fund request.
  final String? sessionFundReason;

  /// F13: Current session balance in balance notification.
  final BigInt? balanceNotificationBalance;

  /// F13: Threshold that triggered notification.
  final BigInt? balanceNotificationThreshold;

  /// F13: Remaining spending limit in notification.
  final BigInt? balanceNotificationSpendingLimitRemaining;

  /// F14: Old session key pubkey being renewed.
  final String? oldSessionKeyPubkey;

  /// F14: Expiry timestamp of the old session key.
  final PlatformInt64? sessionRenewExpiresAt;

  const DecryptedMessage({
    required this.msgType,
    this.paymentId,
    this.merchantDid,
    this.amount,
    this.description,
    this.listCid,
    this.action,
    this.targetDid,
    required this.rawBody,
    this.listType,
    this.label,
    this.newSessionKeyPubkey,
    this.newSessionKeySecretKey,
    this.newSessionKeySpendingLimit,
    this.newSessionKeyDurationSecs,
    this.newSessionKeyScopes,
    this.newSessionKeyTokenMint,
    this.newSessionKeySuggestedSolFunding,
    this.newSessionKeySuggestedTokenFunding,
    this.availablePaymentMethods,
    this.sessionFundRequiredAmount,
    this.sessionFundCurrentBalance,
    this.sessionFundSpendingLimitRemaining,
    this.sessionFundTokenMint,
    this.sessionFundReason,
    this.balanceNotificationBalance,
    this.balanceNotificationThreshold,
    this.balanceNotificationSpendingLimitRemaining,
    this.oldSessionKeyPubkey,
    this.sessionRenewExpiresAt,
  });

  @override
  int get hashCode =>
      msgType.hashCode ^
      paymentId.hashCode ^
      merchantDid.hashCode ^
      amount.hashCode ^
      description.hashCode ^
      listCid.hashCode ^
      action.hashCode ^
      targetDid.hashCode ^
      rawBody.hashCode ^
      listType.hashCode ^
      label.hashCode ^
      newSessionKeyPubkey.hashCode ^
      newSessionKeySecretKey.hashCode ^
      newSessionKeySpendingLimit.hashCode ^
      newSessionKeyDurationSecs.hashCode ^
      newSessionKeyScopes.hashCode ^
      newSessionKeyTokenMint.hashCode ^
      newSessionKeySuggestedSolFunding.hashCode ^
      newSessionKeySuggestedTokenFunding.hashCode ^
      availablePaymentMethods.hashCode ^
      sessionFundRequiredAmount.hashCode ^
      sessionFundCurrentBalance.hashCode ^
      sessionFundSpendingLimitRemaining.hashCode ^
      sessionFundTokenMint.hashCode ^
      sessionFundReason.hashCode ^
      balanceNotificationBalance.hashCode ^
      balanceNotificationThreshold.hashCode ^
      balanceNotificationSpendingLimitRemaining.hashCode ^
      oldSessionKeyPubkey.hashCode ^
      sessionRenewExpiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecryptedMessage &&
          runtimeType == other.runtimeType &&
          msgType == other.msgType &&
          paymentId == other.paymentId &&
          merchantDid == other.merchantDid &&
          amount == other.amount &&
          description == other.description &&
          listCid == other.listCid &&
          action == other.action &&
          targetDid == other.targetDid &&
          rawBody == other.rawBody &&
          listType == other.listType &&
          label == other.label &&
          newSessionKeyPubkey == other.newSessionKeyPubkey &&
          newSessionKeySecretKey == other.newSessionKeySecretKey &&
          newSessionKeySpendingLimit == other.newSessionKeySpendingLimit &&
          newSessionKeyDurationSecs == other.newSessionKeyDurationSecs &&
          newSessionKeyScopes == other.newSessionKeyScopes &&
          newSessionKeyTokenMint == other.newSessionKeyTokenMint &&
          newSessionKeySuggestedSolFunding ==
              other.newSessionKeySuggestedSolFunding &&
          newSessionKeySuggestedTokenFunding ==
              other.newSessionKeySuggestedTokenFunding &&
          availablePaymentMethods == other.availablePaymentMethods &&
          sessionFundRequiredAmount == other.sessionFundRequiredAmount &&
          sessionFundCurrentBalance == other.sessionFundCurrentBalance &&
          sessionFundSpendingLimitRemaining ==
              other.sessionFundSpendingLimitRemaining &&
          sessionFundTokenMint == other.sessionFundTokenMint &&
          sessionFundReason == other.sessionFundReason &&
          balanceNotificationBalance == other.balanceNotificationBalance &&
          balanceNotificationThreshold == other.balanceNotificationThreshold &&
          balanceNotificationSpendingLimitRemaining ==
              other.balanceNotificationSpendingLimitRemaining &&
          oldSessionKeyPubkey == other.oldSessionKeyPubkey &&
          sessionRenewExpiresAt == other.sessionRenewExpiresAt;
}

/// A DIDComm message envelope (before decryption).
class DidcommMessage {
  /// Unique message ID.
  final String msgId;

  /// JWE encrypted envelope.
  final String jweEnvelope;

  /// Unix timestamp when the message was created.
  final PlatformInt64 createdAt;

  const DidcommMessage({
    required this.msgId,
    required this.jweEnvelope,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      msgId.hashCode ^ jweEnvelope.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DidcommMessage &&
          runtimeType == other.runtimeType &&
          msgId == other.msgId &&
          jweEnvelope == other.jweEnvelope &&
          createdAt == other.createdAt;
}
