// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Generate an Ed25519 keypair for the dApp side of Phantom deep link encryption.
Future<PhantomKeypair> phantomGenerateKeypair() =>
    RustLib.instance.api.crateApiPhantomCryptoPhantomGenerateKeypair();

/// Compute the X25519 shared secret.
/// Ed25519 keys are converted to X25519 internally.
Future<String> phantomSharedSecret({
  required String mySecretKeyB64,
  required String theirPublicKeyB64,
}) => RustLib.instance.api.crateApiPhantomCryptoPhantomSharedSecret(
  mySecretKeyB64: mySecretKeyB64,
  theirPublicKeyB64: theirPublicKeyB64,
);

/// NaCl box encrypt using XSalsa20-Poly1305.
Future<String> phantomEncrypt({
  required String sharedSecretB64,
  required String nonceB64,
  required String plaintextB64,
}) => RustLib.instance.api.crateApiPhantomCryptoPhantomEncrypt(
  sharedSecretB64: sharedSecretB64,
  nonceB64: nonceB64,
  plaintextB64: plaintextB64,
);

/// NaCl box decrypt using XSalsa20-Poly1305.
Future<String> phantomDecrypt({
  required String sharedSecretB64,
  required String nonceB64,
  required String ciphertextB64,
}) => RustLib.instance.api.crateApiPhantomCryptoPhantomDecrypt(
  sharedSecretB64: sharedSecretB64,
  nonceB64: nonceB64,
  ciphertextB64: ciphertextB64,
);

/// Keypair for Phantom dApp encryption.
class PhantomKeypair {
  /// Base64url-encoded (no padding) Ed25519 public key (32 bytes).
  final String publicKeyB64;

  /// Base64url-encoded (no padding) Ed25519 secret key (32 bytes seed).
  final String secretKeyB64;

  const PhantomKeypair({
    required this.publicKeyB64,
    required this.secretKeyB64,
  });

  @override
  int get hashCode => publicKeyB64.hashCode ^ secretKeyB64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PhantomKeypair &&
          runtimeType == other.runtimeType &&
          publicKeyB64 == other.publicKeyB64 &&
          secretKeyB64 == other.secretKeyB64;
}
