// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_raw_transaction`, `build_register_ix_data`, `compact_u64_encode`, `derive_session_pda_simple`, `get_recent_blockhash`, `get_session_program_id_bytes`, `is_on_curve`, `send_transaction`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Create a session key for payment authorization.
/// This generates an ephemeral Ed25519 keypair locally and stores it in sled.
/// Returns the session key info without requiring on-chain operations.
Future<SessionKeyInfo> createSessionKey({
  required String storagePath,
  required String ownerPubkey,
  required String targetProgram,
  required List<String> scopes,
  required BigInt spendingLimit,
  required PlatformInt64 durationSecs,
}) => RustLib.instance.api.crateApiSessionCreateSessionKey(
  storagePath: storagePath,
  ownerPubkey: ownerPubkey,
  targetProgram: targetProgram,
  scopes: scopes,
  spendingLimit: spendingLimit,
  durationSecs: durationSecs,
);

/// Create a session key and register it on-chain via JSON-RPC.
///
/// Since solana-sdk can't compile on Windows (OpenSSL dependency),
/// this uses raw JSON-RPC via reqwest + ed25519-dalek to:
/// 1. Generate ephemeral keypair
/// 2. Derive session PDA
/// 3. Build Anchor instruction data
/// 4. Build and sign raw transaction
/// 5. Submit via JSON-RPC sendTransaction
Future<SessionKeyInfo> createAndRegisterSessionKey({
  required String storagePath,
  required String rpcUrl,
  required String ownerSecretKey,
  required String targetProgram,
  required List<String> scopes,
  required BigInt spendingLimit,
  required PlatformInt64 durationSecs,
}) => RustLib.instance.api.crateApiSessionCreateAndRegisterSessionKey(
  storagePath: storagePath,
  rpcUrl: rpcUrl,
  ownerSecretKey: ownerSecretKey,
  targetProgram: targetProgram,
  scopes: scopes,
  spendingLimit: spendingLimit,
  durationSecs: durationSecs,
);

/// Session key information exposed to Flutter.
class SessionKeyInfo {
  /// Base58-encoded ephemeral public key.
  final String ephemeralPubkey;

  /// Base58-encoded ephemeral secret key (64-byte keypair).
  final String ephemeralSecretKey;

  /// Unix timestamp when the session expires.
  final PlatformInt64 expiresAt;

  /// Maximum spending limit in lamports.
  final BigInt spendingLimit;

  /// Permission scopes (e.g. ["sol:transfer", "spl:transfer"]).
  final List<String> scopes;

  /// On-chain registration transaction signature.
  final String? txSignature;

  /// On-chain session PDA address.
  final String? sessionPda;

  const SessionKeyInfo({
    required this.ephemeralPubkey,
    required this.ephemeralSecretKey,
    required this.expiresAt,
    required this.spendingLimit,
    required this.scopes,
    this.txSignature,
    this.sessionPda,
  });

  @override
  int get hashCode =>
      ephemeralPubkey.hashCode ^
      ephemeralSecretKey.hashCode ^
      expiresAt.hashCode ^
      spendingLimit.hashCode ^
      scopes.hashCode ^
      txSignature.hashCode ^
      sessionPda.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionKeyInfo &&
          runtimeType == other.runtimeType &&
          ephemeralPubkey == other.ephemeralPubkey &&
          ephemeralSecretKey == other.ephemeralSecretKey &&
          expiresAt == other.expiresAt &&
          spendingLimit == other.spendingLimit &&
          scopes == other.scopes &&
          txSignature == other.txSignature &&
          sessionPda == other.sessionPda;
}
