// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'cctp_transfer.dart';
import 'channel.dart';
import 'channel_store.dart';
import 'mb_voucher.dart';
import 'notification.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'session.dart';

/// Initialize identity - generates or loads DID from storage.
/// Returns the DID string and DID document JSON.
Future<DidInfo> initializeIdentity({required String storagePath}) => RustLib
    .instance
    .api
    .crateApiSimpleInitializeIdentity(storagePath: storagePath);

/// Get the current DID from the initialized identity.
Future<String> getDid({required String storagePath}) =>
    RustLib.instance.api.crateApiSimpleGetDid(storagePath: storagePath);

/// Connect to mediator WebSocket with auto-reconnect.
Future<void> connectMediator({
  required String storagePath,
  required String wsUrl,
}) => RustLib.instance.api.crateApiSimpleConnectMediator(
  storagePath: storagePath,
  wsUrl: wsUrl,
);

/// Disconnect from the mediator.
Future<void> disconnectMediator() =>
    RustLib.instance.api.crateApiSimpleDisconnectMediator();

/// Register an MCP peer in the DIDComm agent using its DID document.
/// Must be called after pairing so the agent can decrypt authcrypt JWE
/// messages from this peer.
Future<void> registerMcpPeer({
  required String storagePath,
  required String mcpDid,
  required String mcpDidDocJson,
}) => RustLib.instance.api.crateApiSimpleRegisterMcpPeer(
  storagePath: storagePath,
  mcpDid: mcpDid,
  mcpDidDocJson: mcpDidDocJson,
);

/// Send a payment authorization response back to the MCP server.
Future<void> sendAuthResponse({
  required String storagePath,
  required String paymentId,
  required bool authorized,
  required String listAction,
  required String mcpDid,
  SessionKeyInfo? sessionKeyInfo,
  String? listLabel,
  BigInt? listMaxAmount,
  int? dailyTxCountLimit,
  BigInt? perTxLimit,
  String? tokenMint,
  String? paymentMethod,
}) => RustLib.instance.api.crateApiSimpleSendAuthResponse(
  storagePath: storagePath,
  paymentId: paymentId,
  authorized: authorized,
  listAction: listAction,
  mcpDid: mcpDid,
  sessionKeyInfo: sessionKeyInfo,
  listLabel: listLabel,
  listMaxAmount: listMaxAmount,
  dailyTxCountLimit: dailyTxCountLimit,
  perTxLimit: perTxLimit,
  tokenMint: tokenMint,
  paymentMethod: paymentMethod,
);

/// Poll for messages via HTTPS (for FCM wake-up path).
/// Returns a list of DIDComm message envelopes.
Future<List<DidcommMessage>> pullMessages({
  required String mediatorUrl,
  required String token,
  String? afterId,
  required int limit,
}) => RustLib.instance.api.crateApiSimplePullMessages(
  mediatorUrl: mediatorUrl,
  token: token,
  afterId: afterId,
  limit: limit,
);

/// Decrypt a JWE message using the local identity.
/// Optionally accepts MCP peer DID + DID doc so authcrypt JWE from MCP can be verified.
Future<DecryptedMessage> decryptMessage({
  required String storagePath,
  required String jwe,
  String? mcpDid,
  String? mcpDidDocJson,
}) => RustLib.instance.api.crateApiSimpleDecryptMessage(
  storagePath: storagePath,
  jwe: jwe,
  mcpDid: mcpDid,
  mcpDidDocJson: mcpDidDocJson,
);

/// Send a session fund response back to the MCP server.
Future<void> sendSessionFundResponse({
  required String storagePath,
  required String mcpDid,
  required String sessionKeyPubkey,
  required bool funded,
  required BigInt newBalance,
  String? txSignature,
}) => RustLib.instance.api.crateApiSimpleSendSessionFundResponse(
  storagePath: storagePath,
  mcpDid: mcpDid,
  sessionKeyPubkey: sessionKeyPubkey,
  funded: funded,
  newBalance: newBalance,
  txSignature: txSignature,
);

/// Send a session renew response back to the MCP server.
Future<void> sendSessionRenewResponse({
  required String storagePath,
  required String mcpDid,
  required String oldSessionKeyPubkey,
  required String newSessionKeyPubkey,
  required bool renewed,
  String? txSignature,
}) => RustLib.instance.api.crateApiSimpleSendSessionRenewResponse(
  storagePath: storagePath,
  mcpDid: mcpDid,
  oldSessionKeyPubkey: oldSessionKeyPubkey,
  newSessionKeyPubkey: newSessionKeyPubkey,
  renewed: renewed,
  txSignature: txSignature,
);

/// Mock payment signing (placeholder for real signing).
Future<AuthGrant> signPayment({
  required String merchantDid,
  required BigInt amount,
}) => RustLib.instance.api.crateApiSimpleSignPayment(
  merchantDid: merchantDid,
  amount: amount,
);

/// Create a local session key for payment authorization (V2.0).
/// Returns session key info that should be sent to the MCP server via auth response.
Future<SessionKeyInfo> createSessionKeyForPayment({
  required String storagePath,
  required BigInt spendingLimit,
  required PlatformInt64 durationSecs,
  String? tokenMint,
}) => RustLib.instance.api.crateApiSimpleCreateSessionKeyForPayment(
  storagePath: storagePath,
  spendingLimit: spendingLimit,
  durationSecs: durationSecs,
  tokenMint: tokenMint,
);

/// Authenticate with the mediator and get a JWT token.
/// Uses challenge-response: fetches a nonce, signs it with the DID's Ed25519 signing key, and exchanges for JWT.
Future<String> authenticateWithMediator({
  required String mediatorUrl,
  required String storagePath,
  required String did,
}) => RustLib.instance.api.crateApiSimpleAuthenticateWithMediator(
  mediatorUrl: mediatorUrl,
  storagePath: storagePath,
  did: did,
);

/// Register an FCM device token with the mediator.
Future<void> registerDeviceToken({
  required String mediatorUrl,
  required String authToken,
  required String fcmToken,
}) => RustLib.instance.api.crateApiSimpleRegisterDeviceToken(
  mediatorUrl: mediatorUrl,
  authToken: authToken,
  fcmToken: fcmToken,
);

/// Parse an OOB invitation URL (from QR code scan).
/// Extracts the MCP DID, DID document, and mediator WS URL from the invitation.
Future<OobInvitationData> parseOobInvitation({required String invitationUrl}) =>
    RustLib.instance.api.crateApiSimpleParseOobInvitation(
      invitationUrl: invitationUrl,
    );

/// List all session keys stored locally.
Future<List<SessionKeyEntry>> listSessionKeys({required String storagePath}) =>
    RustLib.instance.api.crateApiSimpleListSessionKeys(
      storagePath: storagePath,
    );

/// Find the first active session key.
Future<SessionKeyEntry?> findActiveSessionKey({required String storagePath}) =>
    RustLib.instance.api.crateApiSimpleFindActiveSessionKey(
      storagePath: storagePath,
    );

/// Build an unsigned register-session-key transaction for external wallet signing.
Future<UnsignedRegisterTx> buildUnsignedRegisterTx({
  required String storagePath,
  required String rpcUrl,
  required BigInt spendingLimit,
  required PlatformInt64 durationSecs,
}) => RustLib.instance.api.crateApiSimpleBuildUnsignedRegisterTx(
  storagePath: storagePath,
  rpcUrl: rpcUrl,
  spendingLimit: spendingLimit,
  durationSecs: durationSecs,
);

/// Complete registration after receiving the owner signature from an external wallet.
Future<SessionKeyInfo> completeRegisterWithSignature({
  required String storagePath,
  required String ephemeralPubkey,
  required String ownerSignatureB58,
  required String rpcUrl,
}) => RustLib.instance.api.crateApiSimpleCompleteRegisterWithSignature(
  storagePath: storagePath,
  ephemeralPubkey: ephemeralPubkey,
  ownerSignatureB58: ownerSignatureB58,
  rpcUrl: rpcUrl,
);

/// Revoke a session key on-chain.
Future<String> revokeSessionKeyOnchain({
  required String storagePath,
  required String sessionPubkey,
  required String rpcUrl,
}) => RustLib.instance.api.crateApiSimpleRevokeSessionKeyOnchain(
  storagePath: storagePath,
  sessionPubkey: sessionPubkey,
  rpcUrl: rpcUrl,
);

/// Delete a session key from local storage only.
Future<void> deleteSessionKeyLocal({
  required String storagePath,
  required String sessionPubkey,
}) => RustLib.instance.api.crateApiSimpleDeleteSessionKeyLocal(
  storagePath: storagePath,
  sessionPubkey: sessionPubkey,
);

/// Register an externally-provided session key on-chain (MCP created the keypair).
Future<SessionKeyInfo> registerExternalSessionKey({
  required String storagePath,
  required String rpcUrl,
  required String ownerSecretKey,
  required String ephemeralPubkey,
  required String ephemeralSecretKey,
  required String targetProgram,
  required List<String> scopes,
  required BigInt spendingLimit,
  required PlatformInt64 durationSecs,
  String? tokenMint,
}) => RustLib.instance.api.crateApiSimpleRegisterExternalSessionKey(
  storagePath: storagePath,
  rpcUrl: rpcUrl,
  ownerSecretKey: ownerSecretKey,
  ephemeralPubkey: ephemeralPubkey,
  ephemeralSecretKey: ephemeralSecretKey,
  targetProgram: targetProgram,
  scopes: scopes,
  spendingLimit: spendingLimit,
  durationSecs: durationSecs,
  tokenMint: tokenMint,
);

/// Fund a session key by transferring SOL (and optionally SPL token) from the owner.
Future<List<String>> fundSessionKey({
  required String rpcUrl,
  required String ownerSecretKey,
  required String ephemeralPubkey,
  required BigInt solAmount,
  String? splTokenMint,
  BigInt? splAmount,
}) => RustLib.instance.api.crateApiSimpleFundSessionKey(
  rpcUrl: rpcUrl,
  ownerSecretKey: ownerSecretKey,
  ephemeralPubkey: ephemeralPubkey,
  solAmount: solAmount,
  splTokenMint: splTokenMint,
  splAmount: splAmount,
);

/// Register an externally-provided session key and fund it in one operation.
Future<SessionKeyInfo> registerAndFundSessionKey({
  required String storagePath,
  required String rpcUrl,
  required String ownerSecretKey,
  required String ephemeralPubkey,
  required String ephemeralSecretKey,
  required String targetProgram,
  required List<String> scopes,
  required BigInt spendingLimit,
  required PlatformInt64 durationSecs,
  String? tokenMint,
  required BigInt solFunding,
  BigInt? tokenFunding,
}) => RustLib.instance.api.crateApiSimpleRegisterAndFundSessionKey(
  storagePath: storagePath,
  rpcUrl: rpcUrl,
  ownerSecretKey: ownerSecretKey,
  ephemeralPubkey: ephemeralPubkey,
  ephemeralSecretKey: ephemeralSecretKey,
  targetProgram: targetProgram,
  scopes: scopes,
  spendingLimit: spendingLimit,
  durationSecs: durationSecs,
  tokenMint: tokenMint,
  solFunding: solFunding,
  tokenFunding: tokenFunding,
);

/// Sign a nonce string with the phone's Ed25519 signing key.
/// Returns the base64-no-pad encoded signature.
Future<String> signNonce({
  required String storagePath,
  required String nonce,
}) => RustLib.instance.api.crateApiSimpleSignNonce(
  storagePath: storagePath,
  nonce: nonce,
);

/// Verify an Ed25519 signature from a DID.
/// Returns true if the signature is valid for the given message and DID.
Future<bool> verifyDidSignature({
  required String did,
  required String message,
  required String signatureB64,
}) => RustLib.instance.api.crateApiSimpleVerifyDidSignature(
  did: did,
  message: message,
  signatureB64: signatureB64,
);

/// Drain all queued mediator messages received via the Rust WS connection.
/// Called periodically by the Dart layer to process incoming messages.
Future<List<String>> drainMediatorMessages() =>
    RustLib.instance.api.crateApiSimpleDrainMediatorMessages();

/// Send a connection request to the MCP via the mediator.
/// This is called after parsing the QR code invitation.
Future<void> sendConnectionRequest({
  required String storagePath,
  required String mcpDid,
  required String mcpDidDocJson,
  required String mediatorWsUrl,
  required String pushChannel,
  String? fcmToken,
}) => RustLib.instance.api.crateApiSimpleSendConnectionRequest(
  storagePath: storagePath,
  mcpDid: mcpDid,
  mcpDidDocJson: mcpDidDocJson,
  mediatorWsUrl: mediatorWsUrl,
  pushChannel: pushChannel,
  fcmToken: fcmToken,
);

/// Save a merchant policy to sled.
Future<void> saveMerchantPolicy({
  required String storagePath,
  required String merchantDid,
  required BigInt dailySpendingLimit,
  required int dailyTxCountLimit,
  required BigInt perTxLimit,
  required PlatformInt64 durationSecs,
}) => RustLib.instance.api.crateApiSimpleSaveMerchantPolicy(
  storagePath: storagePath,
  merchantDid: merchantDid,
  dailySpendingLimit: dailySpendingLimit,
  dailyTxCountLimit: dailyTxCountLimit,
  perTxLimit: perTxLimit,
  durationSecs: durationSecs,
);

/// Load a merchant policy from sled.
Future<MerchantPolicy?> loadMerchantPolicy({
  required String storagePath,
  required String merchantDid,
}) => RustLib.instance.api.crateApiSimpleLoadMerchantPolicy(
  storagePath: storagePath,
  merchantDid: merchantDid,
);

/// Parse a payment QR code (ignite://pay?d=... format).
/// Returns merchant DID, amount, description, order ID, and hub endpoint.
Future<PaymentQrData> parsePaymentQr({required String qrData}) =>
    RustLib.instance.api.crateApiSimpleParsePaymentQr(qrData: qrData);

/// List all stored state channels.
Future<List<ChannelInfo>> listChannels({required String storagePath}) =>
    RustLib.instance.api.crateApiSimpleListChannels(storagePath: storagePath);

/// Get channel state info.
Future<ChannelStateInfo> getChannelState({
  required String storagePath,
  required String channelId,
}) => RustLib.instance.api.crateApiSimpleGetChannelState(
  storagePath: storagePath,
  channelId: channelId,
);

/// Open a state channel with a Hub.
Future<OpenChannelResult> openChannel({
  required String storagePath,
  required String hubEndpoint,
  required BigInt deposit,
  required int treeDepth,
}) => RustLib.instance.api.crateApiSimpleOpenChannel(
  storagePath: storagePath,
  hubEndpoint: hubEndpoint,
  deposit: deposit,
  treeDepth: treeDepth,
);

/// Pay through a state channel.
Future<PaymentResult> channelPay({
  required String storagePath,
  required String channelId,
  required String hubEndpoint,
  required BigInt amount,
  required String recipientPubkey,
}) => RustLib.instance.api.crateApiSimpleChannelPay(
  storagePath: storagePath,
  channelId: channelId,
  hubEndpoint: hubEndpoint,
  amount: amount,
  recipientPubkey: recipientPubkey,
);

/// Close a state channel.
Future<String> closeChannel({
  required String storagePath,
  required String channelId,
}) => RustLib.instance.api.crateApiSimpleCloseChannel(
  storagePath: storagePath,
  channelId: channelId,
);

/// Settle a state channel.
Future<String> settleChannel({
  required String storagePath,
  required String channelId,
  required String hubEndpoint,
}) => RustLib.instance.api.crateApiSimpleSettleChannel(
  storagePath: storagePath,
  channelId: channelId,
  hubEndpoint: hubEndpoint,
);

/// Fetch the list of available hubs from the hub registry.
Future<List<HubInfo>> fetchHubList({required String registryUrl}) =>
    RustLib.instance.api.crateApiSimpleFetchHubList(registryUrl: registryUrl);

/// Send a create-channel request to the MCP server via DIDComm.
Future<void> sendCreateChannelRequest({
  required String storagePath,
  required String mcpDid,
  required String hubEndpoint,
  required String providerPubkey,
  required String tokenMint,
  required BigInt deposit,
  required int treeDepth,
}) => RustLib.instance.api.crateApiSimpleSendCreateChannelRequest(
  storagePath: storagePath,
  mcpDid: mcpDid,
  hubEndpoint: hubEndpoint,
  providerPubkey: providerPubkey,
  tokenMint: tokenMint,
  deposit: deposit,
  treeDepth: treeDepth,
);

/// Send an MB deposit request to the MCP server.
/// The MCP deposits into the MagicBlock shared vault and returns mb-deposit-response.
Future<void> sendMbDepositRequest({
  required String storagePath,
  required BigInt amount,
  required String token,
}) => RustLib.instance.api.crateApiSimpleSendMbDepositRequest(
  storagePath: storagePath,
  amount: amount,
  token: token,
);

/// Get or generate the buyer MB keypair, return base58 pubkey.
Future<String> mbGetBuyerPubkey({required String storagePath}) => RustLib
    .instance
    .api
    .crateApiSimpleMbGetBuyerPubkey(storagePath: storagePath);

/// Sign an MB voucher for payment.
Future<MbVoucherResult> mbSignVoucher({
  required String storagePath,
  required String programId,
  required String merchantMbPubkey,
  required BigInt seq,
  required BigInt amount,
}) => RustLib.instance.api.crateApiSimpleMbSignVoucher(
  storagePath: storagePath,
  programId: programId,
  merchantMbPubkey: merchantMbPubkey,
  seq: seq,
  amount: amount,
);

/// Send a QR payment request to the MCP server.
/// Called when user scans a merchant QR code, selects payment method, and confirms.
/// The MCP executes the payment and returns a qr-payment-response.
Future<void> sendQrPaymentRequest({
  required String storagePath,
  required String merchantDid,
  required BigInt amount,
  required String description,
  required String orderId,
  required String paymentMethod,
  required String token,
  required String merchantMediatorUrl,
}) => RustLib.instance.api.crateApiSimpleSendQrPaymentRequest(
  storagePath: storagePath,
  merchantDid: merchantDid,
  amount: amount,
  description: description,
  orderId: orderId,
  paymentMethod: paymentMethod,
  token: token,
  merchantMediatorUrl: merchantMediatorUrl,
);

/// Build an unsigned SOL transfer transaction for direct wallet signing.
/// Bridge wrapper around `session::build_unsigned_transfer_tx`.
Future<String> buildUnsignedTransferTx({
  required String rpcUrl,
  required String walletPubkeyB58,
  required String merchantDid,
  required BigInt amountLamports,
}) => RustLib.instance.api.crateApiSimpleBuildUnsignedTransferTx(
  rpcUrl: rpcUrl,
  walletPubkeyB58: walletPubkeyB58,
  merchantDid: merchantDid,
  amountLamports: amountLamports,
);

/// Send a signed MB voucher to the merchant via DIDComm.
Future<void> mbSendVoucher({
  required String storagePath,
  required String merchantDid,
  required String orderId,
  required String channelId,
  required BigInt seq,
  required BigInt amount,
  required String buyerPubkey,
  required String buyerSig,
}) => RustLib.instance.api.crateApiSimpleMbSendVoucher(
  storagePath: storagePath,
  merchantDid: merchantDid,
  orderId: orderId,
  channelId: channelId,
  seq: seq,
  amount: amount,
  buyerPubkey: buyerPubkey,
  buyerSig: buyerSig,
);

/// Fetch the relayer's fee-payer public key from GET /info.
Future<String> fetchRelayerPubkey({required String relayerUrl}) => RustLib
    .instance
    .api
    .crateApiSimpleFetchRelayerPubkey(relayerUrl: relayerUrl);

/// Build an unsigned sponsored SOL transfer transaction for direct wallet signing.
/// Bridge wrapper around `session::build_unsigned_sponsored_transfer_tx`.
Future<String> buildUnsignedSponsoredTransferTx({
  required String rpcUrl,
  required String walletPubkeyB58,
  required String merchantDid,
  required BigInt amountLamports,
  required String relayerPubkeyB58,
}) => RustLib.instance.api.crateApiSimpleBuildUnsignedSponsoredTransferTx(
  rpcUrl: rpcUrl,
  walletPubkeyB58: walletPubkeyB58,
  merchantDid: merchantDid,
  amountLamports: amountLamports,
  relayerPubkeyB58: relayerPubkeyB58,
);

/// Build an unsigned SPL Token transfer transaction for direct wallet signing.
/// Bridge wrapper around `session::build_unsigned_spl_transfer_tx`.
Future<String> buildUnsignedSplTransferTx({
  required String rpcUrl,
  required String walletPubkeyB58,
  required String merchantWalletB58,
  required BigInt amount,
  required String tokenMintB58,
}) => RustLib.instance.api.crateApiSimpleBuildUnsignedSplTransferTx(
  rpcUrl: rpcUrl,
  walletPubkeyB58: walletPubkeyB58,
  merchantWalletB58: merchantWalletB58,
  amount: amount,
  tokenMintB58: tokenMintB58,
);

/// Build an unsigned sponsored SPL Token transfer transaction for direct wallet signing.
/// Bridge wrapper around `session::build_unsigned_sponsored_spl_transfer_tx`.
Future<String> buildUnsignedSponsoredSplTransferTx({
  required String rpcUrl,
  required String walletPubkeyB58,
  required String merchantWalletB58,
  required BigInt amount,
  required String tokenMintB58,
  required String relayerPubkeyB58,
}) => RustLib.instance.api.crateApiSimpleBuildUnsignedSponsoredSplTransferTx(
  rpcUrl: rpcUrl,
  walletPubkeyB58: walletPubkeyB58,
  merchantWalletB58: merchantWalletB58,
  amount: amount,
  tokenMintB58: tokenMintB58,
  relayerPubkeyB58: relayerPubkeyB58,
);

/// Get SOL balance (lamports) for a pubkey.
Future<BigInt> getSolBalance({
  required String rpcUrl,
  required String pubkeyB58,
}) => RustLib.instance.api.crateApiSimpleGetSolBalance(
  rpcUrl: rpcUrl,
  pubkeyB58: pubkeyB58,
);

/// Get SPL token balance for an owner + mint pair.
Future<BigInt> getTokenBalance({
  required String rpcUrl,
  required String ownerPubkeyB58,
  required String tokenMintB58,
}) => RustLib.instance.api.crateApiSimpleGetTokenBalance(
  rpcUrl: rpcUrl,
  ownerPubkeyB58: ownerPubkeyB58,
  tokenMintB58: tokenMintB58,
);

/// Check if a session key PDA exists on-chain.
Future<SessionOnChainInfo> getSessionAccountInfo({
  required String rpcUrl,
  required String ownerB58,
  required String ephemeralB58,
}) => RustLib.instance.api.crateApiSimpleGetSessionAccountInfo(
  rpcUrl: rpcUrl,
  ownerB58: ownerB58,
  ephemeralB58: ephemeralB58,
);

/// Finalize an already-registered session key by persisting it to local storage.
Future<SessionKeyInfo> finalizeExistingSessionKey({
  required String storagePath,
  required String ownerPubkeyB58,
  required String ephemeralPubkey,
  required SessionOnChainInfo onChainInfo,
  required List<String> scopes,
}) => RustLib.instance.api.crateApiSimpleFinalizeExistingSessionKey(
  storagePath: storagePath,
  ownerPubkeyB58: ownerPubkeyB58,
  ephemeralPubkey: ephemeralPubkey,
  onChainInfo: onChainInfo,
  scopes: scopes,
);

/// Derive the owner's Solana pubkey from the DID stored in sled.
Future<String> getOwnerPubkey({required String storagePath}) =>
    RustLib.instance.api.crateApiSimpleGetOwnerPubkey(storagePath: storagePath);

/// Save a payment authorization record to sled.
Future<void> savePaymentRecord({
  required String storagePath,
  required PaymentRecord record,
}) => RustLib.instance.api.crateApiSimpleSavePaymentRecord(
  storagePath: storagePath,
  record: record,
);

/// List all payment records from sled, newest-first.
Future<List<PaymentRecord>> listPaymentRecords({required String storagePath}) =>
    RustLib.instance.api.crateApiSimpleListPaymentRecords(
      storagePath: storagePath,
    );

/// Get recent transaction signatures for a pubkey.
Future<List<TxHistoryEntry>> getTransactionHistory({
  required String rpcUrl,
  required String pubkeyB58,
  required int limit,
}) => RustLib.instance.api.crateApiSimpleGetTransactionHistory(
  rpcUrl: rpcUrl,
  pubkeyB58: pubkeyB58,
  limit: limit,
);

/// Query CCTP forwarding fees from Circle Iris API.
Future<CctpFeeQuote> cctpGetFees({
  required String irisApiUrl,
  required int srcDomain,
  required int dstDomain,
}) => RustLib.instance.api.crateApiSimpleCctpGetFees(
  irisApiUrl: irisApiUrl,
  srcDomain: srcDomain,
  dstDomain: dstDomain,
);

/// Build ERC-20 approve calldata (USDC → TokenMessengerV2).
Future<String> cctpBuildApproveCalldata({
  required String spender,
  required BigInt amount,
}) => RustLib.instance.api.crateApiSimpleCctpBuildApproveCalldata(
  spender: spender,
  amount: amount,
);

/// Build depositForBurnWithHook calldata for TokenMessengerV2.
Future<String> cctpBuildDepositForBurnCalldata({
  required BigInt amount,
  required int dstDomain,
  required String mintRecipient,
  required String burnToken,
  required String dstCaller,
  required int maxFee,
  required int minFinalityThreshold,
}) => RustLib.instance.api.crateApiSimpleCctpBuildDepositForBurnCalldata(
  amount: amount,
  dstDomain: dstDomain,
  mintRecipient: mintRecipient,
  burnToken: burnToken,
  dstCaller: dstCaller,
  maxFee: maxFee,
  minFinalityThreshold: minFinalityThreshold,
);

/// Derive the Solana USDC ATA for a wallet address (returns hex bytes32).
Future<String> cctpDeriveSolanaUsdcAta({required String walletB58}) => RustLib
    .instance
    .api
    .crateApiSimpleCctpDeriveSolanaUsdcAta(walletB58: walletB58);

/// Poll Circle Iris API for CCTP transfer status.
Future<CctpTransferStatus> cctpPollStatus({
  required String irisApiUrl,
  required int srcDomain,
  required String burnTxHash,
}) => RustLib.instance.api.crateApiSimpleCctpPollStatus(
  irisApiUrl: irisApiUrl,
  srcDomain: srcDomain,
  burnTxHash: burnTxHash,
);

/// Fetch a merchant profile from the DID Registry.
/// On network error or 404, returns an unverified profile with name=None.
Future<MerchantProfile> fetchMerchantProfile({
  required String registryUrl,
  required String merchantDid,
}) => RustLib.instance.api.crateApiSimpleFetchMerchantProfile(
  registryUrl: registryUrl,
  merchantDid: merchantDid,
);

/// Cache a merchant profile in sled under `merchant_profile:{did}`.
Future<void> saveCachedMerchantProfile({
  required String storagePath,
  required MerchantProfile profile,
}) => RustLib.instance.api.crateApiSimpleSaveCachedMerchantProfile(
  storagePath: storagePath,
  profile: profile,
);

/// Load a cached merchant profile from sled. Returns `None` if not cached.
Future<MerchantProfile?> loadCachedMerchantProfile({
  required String storagePath,
  required String merchantDid,
}) => RustLib.instance.api.crateApiSimpleLoadCachedMerchantProfile(
  storagePath: storagePath,
  merchantDid: merchantDid,
);

/// Auth grant returned from payment signing.
class AuthGrant {
  final String merchantDid;
  final BigInt amount;
  final String signature;

  const AuthGrant({
    required this.merchantDid,
    required this.amount,
    required this.signature,
  });

  @override
  int get hashCode =>
      merchantDid.hashCode ^ amount.hashCode ^ signature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthGrant &&
          runtimeType == other.runtimeType &&
          merchantDid == other.merchantDid &&
          amount == other.amount &&
          signature == other.signature;
}

/// Return type for the DID identity info.
class DidInfo {
  final String did;
  final String didDocJson;

  const DidInfo({required this.did, required this.didDocJson});

  @override
  int get hashCode => did.hashCode ^ didDocJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DidInfo &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          didDocJson == other.didDocJson;
}

/// Hub info from the registry.
class HubInfo {
  final String hubId;
  final String hubDid;
  final String endpointUrl;
  final String name;
  final String description;
  final String status;
  final int feeRateBps;
  final BigInt availableLiquidity;
  final int onlineRate;
  final int successRate;
  final int avgLatencyMs;
  final int activeChannels;
  final List<String> supportedTokens;

  const HubInfo({
    required this.hubId,
    required this.hubDid,
    required this.endpointUrl,
    required this.name,
    required this.description,
    required this.status,
    required this.feeRateBps,
    required this.availableLiquidity,
    required this.onlineRate,
    required this.successRate,
    required this.avgLatencyMs,
    required this.activeChannels,
    required this.supportedTokens,
  });

  @override
  int get hashCode =>
      hubId.hashCode ^
      hubDid.hashCode ^
      endpointUrl.hashCode ^
      name.hashCode ^
      description.hashCode ^
      status.hashCode ^
      feeRateBps.hashCode ^
      availableLiquidity.hashCode ^
      onlineRate.hashCode ^
      successRate.hashCode ^
      avgLatencyMs.hashCode ^
      activeChannels.hashCode ^
      supportedTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HubInfo &&
          runtimeType == other.runtimeType &&
          hubId == other.hubId &&
          hubDid == other.hubDid &&
          endpointUrl == other.endpointUrl &&
          name == other.name &&
          description == other.description &&
          status == other.status &&
          feeRateBps == other.feeRateBps &&
          availableLiquidity == other.availableLiquidity &&
          onlineRate == other.onlineRate &&
          successRate == other.successRate &&
          avgLatencyMs == other.avgLatencyMs &&
          activeChannels == other.activeChannels &&
          supportedTokens == other.supportedTokens;
}

/// Merchant profile resolved from the DID Registry.
class MerchantProfile {
  final String did;
  final bool verified;
  final String? name;
  final String? category;

  const MerchantProfile({
    required this.did,
    required this.verified,
    this.name,
    this.category,
  });

  @override
  int get hashCode =>
      did.hashCode ^ verified.hashCode ^ name.hashCode ^ category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MerchantProfile &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          verified == other.verified &&
          name == other.name &&
          category == other.category;
}

/// Parsed OOB invitation data.
class OobInvitationData {
  final String mcpDid;
  final String didDocJson;
  final String mediatorWsUrl;
  final String label;

  const OobInvitationData({
    required this.mcpDid,
    required this.didDocJson,
    required this.mediatorWsUrl,
    required this.label,
  });

  @override
  int get hashCode =>
      mcpDid.hashCode ^
      didDocJson.hashCode ^
      mediatorWsUrl.hashCode ^
      label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OobInvitationData &&
          runtimeType == other.runtimeType &&
          mcpDid == other.mcpDid &&
          didDocJson == other.didDocJson &&
          mediatorWsUrl == other.mediatorWsUrl &&
          label == other.label;
}
