// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'notification.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'session.dart';

/// Initialize identity - generates or loads DID from storage.
/// Returns the DID string and DID document JSON.
Future<DidInfo> initializeIdentity({required String storagePath}) => RustLib
    .instance
    .api
    .crateApiSimpleInitializeIdentity(storagePath: storagePath);

/// Get the current DID from the initialized identity.
Future<String> getDid({required String storagePath}) =>
    RustLib.instance.api.crateApiSimpleGetDid(storagePath: storagePath);

/// Connect to mediator WebSocket with auto-reconnect.
Future<void> connectMediator({
  required String storagePath,
  required String wsUrl,
}) => RustLib.instance.api.crateApiSimpleConnectMediator(
  storagePath: storagePath,
  wsUrl: wsUrl,
);

/// Disconnect from the mediator.
Future<void> disconnectMediator() =>
    RustLib.instance.api.crateApiSimpleDisconnectMediator();

/// Send a payment authorization response back to the MCP server.
Future<void> sendAuthResponse({
  required String storagePath,
  required String paymentId,
  required bool authorized,
  required String listAction,
  required String mcpDid,
  SessionKeyInfo? sessionKeyInfo,
  String? listLabel,
  BigInt? listMaxAmount,
  int? dailyTxCountLimit,
  BigInt? perTxLimit,
}) => RustLib.instance.api.crateApiSimpleSendAuthResponse(
  storagePath: storagePath,
  paymentId: paymentId,
  authorized: authorized,
  listAction: listAction,
  mcpDid: mcpDid,
  sessionKeyInfo: sessionKeyInfo,
  listLabel: listLabel,
  listMaxAmount: listMaxAmount,
  dailyTxCountLimit: dailyTxCountLimit,
  perTxLimit: perTxLimit,
);

/// Poll for messages via HTTPS (for FCM wake-up path).
/// Returns a list of DIDComm message envelopes.
Future<List<DidcommMessage>> pullMessages({
  required String mediatorUrl,
  required String token,
  String? afterId,
  required int limit,
}) => RustLib.instance.api.crateApiSimplePullMessages(
  mediatorUrl: mediatorUrl,
  token: token,
  afterId: afterId,
  limit: limit,
);

/// Decrypt a JWE message using the local identity.
Future<DecryptedMessage> decryptMessage({
  required String storagePath,
  required String jwe,
}) => RustLib.instance.api.crateApiSimpleDecryptMessage(
  storagePath: storagePath,
  jwe: jwe,
);

/// Mock payment signing (placeholder for real signing).
Future<AuthGrant> signPayment({
  required String merchantDid,
  required BigInt amount,
}) => RustLib.instance.api.crateApiSimpleSignPayment(
  merchantDid: merchantDid,
  amount: amount,
);

/// Create a local session key for payment authorization (V2.0).
/// Returns session key info that should be sent to the MCP server via auth response.
Future<SessionKeyInfo> createSessionKeyForPayment({
  required String storagePath,
  required BigInt spendingLimit,
  required PlatformInt64 durationSecs,
}) => RustLib.instance.api.crateApiSimpleCreateSessionKeyForPayment(
  storagePath: storagePath,
  spendingLimit: spendingLimit,
  durationSecs: durationSecs,
);

/// Authenticate with the mediator and get a JWT token.
/// Uses challenge-response: fetches a nonce, signs it with the DID key, and exchanges for JWT.
Future<String> authenticateWithMediator({
  required String mediatorUrl,
  required String did,
}) => RustLib.instance.api.crateApiSimpleAuthenticateWithMediator(
  mediatorUrl: mediatorUrl,
  did: did,
);

/// Register an FCM device token with the mediator.
Future<void> registerDeviceToken({
  required String mediatorUrl,
  required String authToken,
  required String fcmToken,
}) => RustLib.instance.api.crateApiSimpleRegisterDeviceToken(
  mediatorUrl: mediatorUrl,
  authToken: authToken,
  fcmToken: fcmToken,
);

/// Parse an OOB invitation URL (from QR code scan).
/// Extracts the MCP DID, DID document, and mediator WS URL from the invitation.
Future<OobInvitationData> parseOobInvitation({required String invitationUrl}) =>
    RustLib.instance.api.crateApiSimpleParseOobInvitation(
      invitationUrl: invitationUrl,
    );

/// List all session keys stored locally.
Future<List<SessionKeyEntry>> listSessionKeys({required String storagePath}) =>
    RustLib.instance.api.crateApiSimpleListSessionKeys(
      storagePath: storagePath,
    );

/// Find the first active session key.
Future<SessionKeyEntry?> findActiveSessionKey({required String storagePath}) =>
    RustLib.instance.api.crateApiSimpleFindActiveSessionKey(
      storagePath: storagePath,
    );

/// Build an unsigned register-session-key transaction for external wallet signing.
Future<UnsignedRegisterTx> buildUnsignedRegisterTx({
  required String storagePath,
  required String rpcUrl,
  required BigInt spendingLimit,
  required PlatformInt64 durationSecs,
}) => RustLib.instance.api.crateApiSimpleBuildUnsignedRegisterTx(
  storagePath: storagePath,
  rpcUrl: rpcUrl,
  spendingLimit: spendingLimit,
  durationSecs: durationSecs,
);

/// Complete registration after receiving the owner signature from an external wallet.
Future<SessionKeyInfo> completeRegisterWithSignature({
  required String storagePath,
  required String ephemeralPubkey,
  required String ownerSignatureB58,
  required String rpcUrl,
}) => RustLib.instance.api.crateApiSimpleCompleteRegisterWithSignature(
  storagePath: storagePath,
  ephemeralPubkey: ephemeralPubkey,
  ownerSignatureB58: ownerSignatureB58,
  rpcUrl: rpcUrl,
);

/// Revoke a session key on-chain.
Future<String> revokeSessionKeyOnchain({
  required String storagePath,
  required String sessionPubkey,
  required String rpcUrl,
}) => RustLib.instance.api.crateApiSimpleRevokeSessionKeyOnchain(
  storagePath: storagePath,
  sessionPubkey: sessionPubkey,
  rpcUrl: rpcUrl,
);

/// Delete a session key from local storage only.
Future<void> deleteSessionKeyLocal({
  required String storagePath,
  required String sessionPubkey,
}) => RustLib.instance.api.crateApiSimpleDeleteSessionKeyLocal(
  storagePath: storagePath,
  sessionPubkey: sessionPubkey,
);

/// Send a connection request to the MCP via the mediator.
/// This is called after parsing the QR code invitation.
Future<void> sendConnectionRequest({
  required String storagePath,
  required String mcpDid,
  required String mcpDidDocJson,
  required String mediatorWsUrl,
  required String pushChannel,
  String? fcmToken,
}) => RustLib.instance.api.crateApiSimpleSendConnectionRequest(
  storagePath: storagePath,
  mcpDid: mcpDid,
  mcpDidDocJson: mcpDidDocJson,
  mediatorWsUrl: mediatorWsUrl,
  pushChannel: pushChannel,
  fcmToken: fcmToken,
);

/// Save a merchant policy to sled.
Future<void> saveMerchantPolicy({
  required String storagePath,
  required String merchantDid,
  required BigInt dailySpendingLimit,
  required int dailyTxCountLimit,
  required BigInt perTxLimit,
  required PlatformInt64 durationSecs,
}) => RustLib.instance.api.crateApiSimpleSaveMerchantPolicy(
  storagePath: storagePath,
  merchantDid: merchantDid,
  dailySpendingLimit: dailySpendingLimit,
  dailyTxCountLimit: dailyTxCountLimit,
  perTxLimit: perTxLimit,
  durationSecs: durationSecs,
);

/// Load a merchant policy from sled.
Future<MerchantPolicy?> loadMerchantPolicy({
  required String storagePath,
  required String merchantDid,
}) => RustLib.instance.api.crateApiSimpleLoadMerchantPolicy(
  storagePath: storagePath,
  merchantDid: merchantDid,
);

/// Auth grant returned from payment signing.
class AuthGrant {
  final String merchantDid;
  final BigInt amount;
  final String signature;

  const AuthGrant({
    required this.merchantDid,
    required this.amount,
    required this.signature,
  });

  @override
  int get hashCode =>
      merchantDid.hashCode ^ amount.hashCode ^ signature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthGrant &&
          runtimeType == other.runtimeType &&
          merchantDid == other.merchantDid &&
          amount == other.amount &&
          signature == other.signature;
}

/// Return type for the DID identity info.
class DidInfo {
  final String did;
  final String didDocJson;

  const DidInfo({required this.did, required this.didDocJson});

  @override
  int get hashCode => did.hashCode ^ didDocJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DidInfo &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          didDocJson == other.didDocJson;
}

/// Parsed OOB invitation data.
class OobInvitationData {
  final String mcpDid;
  final String didDocJson;
  final String mediatorWsUrl;
  final String label;

  const OobInvitationData({
    required this.mcpDid,
    required this.didDocJson,
    required this.mediatorWsUrl,
    required this.label,
  });

  @override
  int get hashCode =>
      mcpDid.hashCode ^
      didDocJson.hashCode ^
      mediatorWsUrl.hashCode ^
      label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OobInvitationData &&
          runtimeType == other.runtimeType &&
          mcpDid == other.mcpDid &&
          didDocJson == other.didDocJson &&
          mediatorWsUrl == other.mediatorWsUrl &&
          label == other.label;
}
