// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/cctp_transfer.dart';
import 'api/channel.dart';
import 'api/channel_store.dart';
import 'api/mb_voucher.dart';
import 'api/notification.dart';
import 'api/phantom_crypto.dart';
import 'api/session.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthGrant dco_decode_auth_grant(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MerchantPolicy dco_decode_box_autoadd_merchant_policy(dynamic raw);

  @protected
  MerchantProfile dco_decode_box_autoadd_merchant_profile(dynamic raw);

  @protected
  PaymentRecord dco_decode_box_autoadd_payment_record(dynamic raw);

  @protected
  SessionKeyEntry dco_decode_box_autoadd_session_key_entry(dynamic raw);

  @protected
  SessionKeyInfo dco_decode_box_autoadd_session_key_info(dynamic raw);

  @protected
  SessionOnChainInfo dco_decode_box_autoadd_session_on_chain_info(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CctpFeeQuote dco_decode_cctp_fee_quote(dynamic raw);

  @protected
  CctpTransferStatus dco_decode_cctp_transfer_status(dynamic raw);

  @protected
  ChannelInfo dco_decode_channel_info(dynamic raw);

  @protected
  ChannelStateInfo dco_decode_channel_state_info(dynamic raw);

  @protected
  DecryptedMessage dco_decode_decrypted_message(dynamic raw);

  @protected
  DidInfo dco_decode_did_info(dynamic raw);

  @protected
  DidcommMessage dco_decode_didcomm_message(dynamic raw);

  @protected
  HubInfo dco_decode_hub_info(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ChannelInfo> dco_decode_list_channel_info(dynamic raw);

  @protected
  List<DidcommMessage> dco_decode_list_didcomm_message(dynamic raw);

  @protected
  List<HubInfo> dco_decode_list_hub_info(dynamic raw);

  @protected
  List<PaymentRecord> dco_decode_list_payment_record(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SessionKeyEntry> dco_decode_list_session_key_entry(dynamic raw);

  @protected
  List<TxHistoryEntry> dco_decode_list_tx_history_entry(dynamic raw);

  @protected
  MbVoucherResult dco_decode_mb_voucher_result(dynamic raw);

  @protected
  MerchantPolicy dco_decode_merchant_policy(dynamic raw);

  @protected
  MerchantProfile dco_decode_merchant_profile(dynamic raw);

  @protected
  OobInvitationData dco_decode_oob_invitation_data(dynamic raw);

  @protected
  OpenChannelResult dco_decode_open_channel_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MerchantPolicy? dco_decode_opt_box_autoadd_merchant_policy(dynamic raw);

  @protected
  MerchantProfile? dco_decode_opt_box_autoadd_merchant_profile(dynamic raw);

  @protected
  SessionKeyEntry? dco_decode_opt_box_autoadd_session_key_entry(dynamic raw);

  @protected
  SessionKeyInfo? dco_decode_opt_box_autoadd_session_key_info(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  PaymentQrData dco_decode_payment_qr_data(dynamic raw);

  @protected
  PaymentRecord dco_decode_payment_record(dynamic raw);

  @protected
  PaymentResult dco_decode_payment_result(dynamic raw);

  @protected
  PhantomKeypair dco_decode_phantom_keypair(dynamic raw);

  @protected
  SessionKeyEntry dco_decode_session_key_entry(dynamic raw);

  @protected
  SessionKeyInfo dco_decode_session_key_info(dynamic raw);

  @protected
  SessionOnChainInfo dco_decode_session_on_chain_info(dynamic raw);

  @protected
  TxHistoryEntry dco_decode_tx_history_entry(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnsignedRegisterTx dco_decode_unsigned_register_tx(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthGrant sse_decode_auth_grant(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MerchantPolicy sse_decode_box_autoadd_merchant_policy(
    SseDeserializer deserializer,
  );

  @protected
  MerchantProfile sse_decode_box_autoadd_merchant_profile(
    SseDeserializer deserializer,
  );

  @protected
  PaymentRecord sse_decode_box_autoadd_payment_record(
    SseDeserializer deserializer,
  );

  @protected
  SessionKeyEntry sse_decode_box_autoadd_session_key_entry(
    SseDeserializer deserializer,
  );

  @protected
  SessionKeyInfo sse_decode_box_autoadd_session_key_info(
    SseDeserializer deserializer,
  );

  @protected
  SessionOnChainInfo sse_decode_box_autoadd_session_on_chain_info(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CctpFeeQuote sse_decode_cctp_fee_quote(SseDeserializer deserializer);

  @protected
  CctpTransferStatus sse_decode_cctp_transfer_status(
    SseDeserializer deserializer,
  );

  @protected
  ChannelInfo sse_decode_channel_info(SseDeserializer deserializer);

  @protected
  ChannelStateInfo sse_decode_channel_state_info(SseDeserializer deserializer);

  @protected
  DecryptedMessage sse_decode_decrypted_message(SseDeserializer deserializer);

  @protected
  DidInfo sse_decode_did_info(SseDeserializer deserializer);

  @protected
  DidcommMessage sse_decode_didcomm_message(SseDeserializer deserializer);

  @protected
  HubInfo sse_decode_hub_info(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ChannelInfo> sse_decode_list_channel_info(SseDeserializer deserializer);

  @protected
  List<DidcommMessage> sse_decode_list_didcomm_message(
    SseDeserializer deserializer,
  );

  @protected
  List<HubInfo> sse_decode_list_hub_info(SseDeserializer deserializer);

  @protected
  List<PaymentRecord> sse_decode_list_payment_record(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SessionKeyEntry> sse_decode_list_session_key_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<TxHistoryEntry> sse_decode_list_tx_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  MbVoucherResult sse_decode_mb_voucher_result(SseDeserializer deserializer);

  @protected
  MerchantPolicy sse_decode_merchant_policy(SseDeserializer deserializer);

  @protected
  MerchantProfile sse_decode_merchant_profile(SseDeserializer deserializer);

  @protected
  OobInvitationData sse_decode_oob_invitation_data(
    SseDeserializer deserializer,
  );

  @protected
  OpenChannelResult sse_decode_open_channel_result(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MerchantPolicy? sse_decode_opt_box_autoadd_merchant_policy(
    SseDeserializer deserializer,
  );

  @protected
  MerchantProfile? sse_decode_opt_box_autoadd_merchant_profile(
    SseDeserializer deserializer,
  );

  @protected
  SessionKeyEntry? sse_decode_opt_box_autoadd_session_key_entry(
    SseDeserializer deserializer,
  );

  @protected
  SessionKeyInfo? sse_decode_opt_box_autoadd_session_key_info(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  PaymentQrData sse_decode_payment_qr_data(SseDeserializer deserializer);

  @protected
  PaymentRecord sse_decode_payment_record(SseDeserializer deserializer);

  @protected
  PaymentResult sse_decode_payment_result(SseDeserializer deserializer);

  @protected
  PhantomKeypair sse_decode_phantom_keypair(SseDeserializer deserializer);

  @protected
  SessionKeyEntry sse_decode_session_key_entry(SseDeserializer deserializer);

  @protected
  SessionKeyInfo sse_decode_session_key_info(SseDeserializer deserializer);

  @protected
  SessionOnChainInfo sse_decode_session_on_chain_info(
    SseDeserializer deserializer,
  );

  @protected
  TxHistoryEntry sse_decode_tx_history_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnsignedRegisterTx sse_decode_unsigned_register_tx(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_auth_grant(AuthGrant self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_merchant_policy(
    MerchantPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_merchant_profile(
    MerchantProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_payment_record(
    PaymentRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_key_entry(
    SessionKeyEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_key_info(
    SessionKeyInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_on_chain_info(
    SessionOnChainInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_cctp_fee_quote(CctpFeeQuote self, SseSerializer serializer);

  @protected
  void sse_encode_cctp_transfer_status(
    CctpTransferStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_channel_info(ChannelInfo self, SseSerializer serializer);

  @protected
  void sse_encode_channel_state_info(
    ChannelStateInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_decrypted_message(
    DecryptedMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_did_info(DidInfo self, SseSerializer serializer);

  @protected
  void sse_encode_didcomm_message(
    DidcommMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hub_info(HubInfo self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_channel_info(
    List<ChannelInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_didcomm_message(
    List<DidcommMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_hub_info(List<HubInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_payment_record(
    List<PaymentRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_key_entry(
    List<SessionKeyEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tx_history_entry(
    List<TxHistoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mb_voucher_result(
    MbVoucherResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merchant_policy(
    MerchantPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merchant_profile(
    MerchantProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_oob_invitation_data(
    OobInvitationData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_open_channel_result(
    OpenChannelResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_merchant_policy(
    MerchantPolicy? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_merchant_profile(
    MerchantProfile? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_session_key_entry(
    SessionKeyEntry? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_session_key_info(
    SessionKeyInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_payment_qr_data(PaymentQrData self, SseSerializer serializer);

  @protected
  void sse_encode_payment_record(PaymentRecord self, SseSerializer serializer);

  @protected
  void sse_encode_payment_result(PaymentResult self, SseSerializer serializer);

  @protected
  void sse_encode_phantom_keypair(
    PhantomKeypair self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_key_entry(
    SessionKeyEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_key_info(
    SessionKeyInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_on_chain_info(
    SessionOnChainInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tx_history_entry(
    TxHistoryEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unsigned_register_tx(
    UnsignedRegisterTx self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
