// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi-Z1xYF76B6OBrfqGkQvEBdGk3918rMs',
    appId: '1:261974165617:web:af8b73704e92e4956f73d0',
    messagingSenderId: '261974165617',
    projectId: 'ignite-pay-merchant',
    authDomain: 'ignite-pay-merchant.firebaseapp.com',
    storageBucket: 'ignite-pay-merchant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHe8hiaPRTudUPPqcTIfBlt7dsiJXRlRo',
    appId: '1:261974165617:android:aeefebe08c7e09016f73d0',
    messagingSenderId: '261974165617',
    projectId: 'ignite-pay-merchant',
    storageBucket: 'ignite-pay-merchant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANoWLXViMIzXwKopUgJmddaC8wJcCouzY',
    appId: '1:261974165617:ios:940d955e5a0e76286f73d0',
    messagingSenderId: '261974165617',
    projectId: 'ignite-pay-merchant',
    storageBucket: 'ignite-pay-merchant.firebasestorage.app',
    iosBundleId: 'com.ignitepay.ignitePayMerchantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANoWLXViMIzXwKopUgJmddaC8wJcCouzY',
    appId: '1:261974165617:ios:940d955e5a0e76286f73d0',
    messagingSenderId: '261974165617',
    projectId: 'ignite-pay-merchant',
    storageBucket: 'ignite-pay-merchant.firebasestorage.app',
    iosBundleId: 'com.ignitepay.ignitePayMerchantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi-Z1xYF76B6OBrfqGkQvEBdGk3918rMs',
    appId: '1:261974165617:web:c880d13c49111a756f73d0',
    messagingSenderId: '261974165617',
    projectId: 'ignite-pay-merchant',
    authDomain: 'ignite-pay-merchant.firebaseapp.com',
    storageBucket: 'ignite-pay-merchant.firebasestorage.app',
  );
}
