// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/merchant.dart';
import 'api/merchant_didcomm.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 915218740;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_ignite_pay_merchant_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiMerchantAppendAudit({
    required String storagePath,
    required String eventType,
    String? orderId,
    BigInt? amount,
    required String detail,
  });

  Future<String> crateApiMerchantDidcommAuthenticateWithMediator({
    required String mediatorUrl,
    required String storagePath,
    required String did,
  });

  Future<void> crateApiMerchantConfirmOrder({
    required String storagePath,
    required String orderId,
    required String channelId,
    required int leafIndex,
    required BigInt sequence,
  });

  Future<void> crateApiMerchantDidcommConnectMediator({
    required String storagePath,
    required String wsUrl,
  });

  Future<DecryptedMessage> crateApiMerchantDidcommDecryptMessage({
    required String storagePath,
    required String jwe,
  });

  Future<void> crateApiMerchantDidcommDisconnectMediator();

  Future<List<HubInfo>> crateApiMerchantDidcommFetchHubList({
    required String registryUrl,
  });

  Future<String> crateApiMerchantGenerateMerchantKeypair({
    required String storagePath,
  });

  Future<String> crateApiMerchantGeneratePaymentQr({
    required String merchantDid,
    required BigInt amount,
    required String description,
    required String hubEndpoint,
    required String merchantMbPubkey,
  });

  Future<String> crateApiMerchantGenerateQrAscii({required String qrText});

  Future<String> crateApiMerchantGetMbMerchantPubkey({
    required String storagePath,
  });

  Future<String> crateApiMerchantGetMerchantDid({required String storagePath});

  Future<String> crateApiMerchantGetMerchantPubkey({
    required String storagePath,
  });

  Future<PaymentOrderBridge?> crateApiMerchantGetOrder({
    required String storagePath,
    required String orderId,
  });

  Future<List<PaymentOrderBridge>> crateApiMerchantGetPendingOrders({
    required String storagePath,
  });

  Future<String> crateApiMerchantInitializeMbMerchant({
    required String storagePath,
  });

  Future<DidInfo> crateApiMerchantInitializeMerchant({
    required String storagePath,
  });

  Future<DidInfo> crateApiMerchantDidcommInitializeMerchantComm({
    required String storagePath,
  });

  Future<List<PaymentOrderBridge>> crateApiMerchantListOrders({
    required String storagePath,
    required int limit,
  });

  Future<OobInvitationData> crateApiMerchantDidcommParseOobInvitation({
    required String invitationUrl,
  });

  Future<List<DidcommMessage>> crateApiMerchantDidcommPullMessages({
    required String mediatorUrl,
    required String token,
    String? afterId,
    required int limit,
  });

  Future<List<AuditEntryBridge>> crateApiMerchantRecentAudit({
    required String storagePath,
    required int limit,
  });

  Future<void> crateApiMerchantDidcommRegisterDeviceToken({
    required String mediatorUrl,
    required String authToken,
    required String fcmToken,
  });

  Future<void> crateApiMerchantDidcommSendConnectionRequest({
    required String storagePath,
    required String mcpDid,
    required String mcpDidDocJson,
    required String mediatorWsUrl,
    required String pushChannel,
    String? fcmToken,
    String? appMediatorWsUrl,
    String? appMediatorHttpUrl,
  });

  Future<void> crateApiMerchantDidcommSendCreateChannelRequest({
    required String storagePath,
    required String mcpDid,
    required String hubEndpoint,
    required String providerPubkey,
    required String tokenMint,
    required BigInt deposit,
    required int treeDepth,
  });

  Future<void> crateApiMerchantDidcommSendMediatorUpdate({
    required String storagePath,
    required String peerDid,
    required String peerDidDocJson,
    required String mcpMediatorHttpUrl,
    required String mediatorHttpUrl,
    required String mediatorWsUrl,
  });

  Future<String> crateApiMerchantDidcommSignNonce({
    required String storagePath,
    required String nonce,
  });

  Future<bool> crateApiMerchantDidcommVerifyDidSignature({
    required String did,
    required String message,
    required String signatureB64,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiMerchantAppendAudit({
    required String storagePath,
    required String eventType,
    String? orderId,
    BigInt? amount,
    required String detail,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          sse_encode_String(eventType, serializer);
          sse_encode_opt_String(orderId, serializer);
          sse_encode_opt_box_autoadd_u_64(amount, serializer);
          sse_encode_String(detail, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantAppendAuditConstMeta,
        argValues: [storagePath, eventType, orderId, amount, detail],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantAppendAuditConstMeta =>
      const TaskConstMeta(
        debugName: "append_audit",
        argNames: ["storagePath", "eventType", "orderId", "amount", "detail"],
      );

  @override
  Future<String> crateApiMerchantDidcommAuthenticateWithMediator({
    required String mediatorUrl,
    required String storagePath,
    required String did,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mediatorUrl, serializer);
          sse_encode_String(storagePath, serializer);
          sse_encode_String(did, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommAuthenticateWithMediatorConstMeta,
        argValues: [mediatorUrl, storagePath, did],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommAuthenticateWithMediatorConstMeta =>
      const TaskConstMeta(
        debugName: "authenticate_with_mediator",
        argNames: ["mediatorUrl", "storagePath", "did"],
      );

  @override
  Future<void> crateApiMerchantConfirmOrder({
    required String storagePath,
    required String orderId,
    required String channelId,
    required int leafIndex,
    required BigInt sequence,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          sse_encode_String(orderId, serializer);
          sse_encode_String(channelId, serializer);
          sse_encode_u_32(leafIndex, serializer);
          sse_encode_u_64(sequence, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantConfirmOrderConstMeta,
        argValues: [storagePath, orderId, channelId, leafIndex, sequence],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantConfirmOrderConstMeta =>
      const TaskConstMeta(
        debugName: "confirm_order",
        argNames: [
          "storagePath",
          "orderId",
          "channelId",
          "leafIndex",
          "sequence",
        ],
      );

  @override
  Future<void> crateApiMerchantDidcommConnectMediator({
    required String storagePath,
    required String wsUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          sse_encode_String(wsUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommConnectMediatorConstMeta,
        argValues: [storagePath, wsUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommConnectMediatorConstMeta =>
      const TaskConstMeta(
        debugName: "connect_mediator",
        argNames: ["storagePath", "wsUrl"],
      );

  @override
  Future<DecryptedMessage> crateApiMerchantDidcommDecryptMessage({
    required String storagePath,
    required String jwe,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          sse_encode_String(jwe, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_decrypted_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommDecryptMessageConstMeta,
        argValues: [storagePath, jwe],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommDecryptMessageConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_message",
        argNames: ["storagePath", "jwe"],
      );

  @override
  Future<void> crateApiMerchantDidcommDisconnectMediator() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommDisconnectMediatorConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommDisconnectMediatorConstMeta =>
      const TaskConstMeta(debugName: "disconnect_mediator", argNames: []);

  @override
  Future<List<HubInfo>> crateApiMerchantDidcommFetchHubList({
    required String registryUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(registryUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_hub_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommFetchHubListConstMeta,
        argValues: [registryUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommFetchHubListConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_hub_list",
        argNames: ["registryUrl"],
      );

  @override
  Future<String> crateApiMerchantGenerateMerchantKeypair({
    required String storagePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantGenerateMerchantKeypairConstMeta,
        argValues: [storagePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantGenerateMerchantKeypairConstMeta =>
      const TaskConstMeta(
        debugName: "generate_merchant_keypair",
        argNames: ["storagePath"],
      );

  @override
  Future<String> crateApiMerchantGeneratePaymentQr({
    required String merchantDid,
    required BigInt amount,
    required String description,
    required String hubEndpoint,
    required String merchantMbPubkey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(merchantDid, serializer);
          sse_encode_u_64(amount, serializer);
          sse_encode_String(description, serializer);
          sse_encode_String(hubEndpoint, serializer);
          sse_encode_String(merchantMbPubkey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantGeneratePaymentQrConstMeta,
        argValues: [
          merchantDid,
          amount,
          description,
          hubEndpoint,
          merchantMbPubkey,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantGeneratePaymentQrConstMeta =>
      const TaskConstMeta(
        debugName: "generate_payment_qr",
        argNames: [
          "merchantDid",
          "amount",
          "description",
          "hubEndpoint",
          "merchantMbPubkey",
        ],
      );

  @override
  Future<String> crateApiMerchantGenerateQrAscii({required String qrText}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(qrText, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantGenerateQrAsciiConstMeta,
        argValues: [qrText],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantGenerateQrAsciiConstMeta =>
      const TaskConstMeta(debugName: "generate_qr_ascii", argNames: ["qrText"]);

  @override
  Future<String> crateApiMerchantGetMbMerchantPubkey({
    required String storagePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantGetMbMerchantPubkeyConstMeta,
        argValues: [storagePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantGetMbMerchantPubkeyConstMeta =>
      const TaskConstMeta(
        debugName: "get_mb_merchant_pubkey",
        argNames: ["storagePath"],
      );

  @override
  Future<String> crateApiMerchantGetMerchantDid({required String storagePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantGetMerchantDidConstMeta,
        argValues: [storagePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantGetMerchantDidConstMeta =>
      const TaskConstMeta(
        debugName: "get_merchant_did",
        argNames: ["storagePath"],
      );

  @override
  Future<String> crateApiMerchantGetMerchantPubkey({
    required String storagePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantGetMerchantPubkeyConstMeta,
        argValues: [storagePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantGetMerchantPubkeyConstMeta =>
      const TaskConstMeta(
        debugName: "get_merchant_pubkey",
        argNames: ["storagePath"],
      );

  @override
  Future<PaymentOrderBridge?> crateApiMerchantGetOrder({
    required String storagePath,
    required String orderId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          sse_encode_String(orderId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_payment_order_bridge,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantGetOrderConstMeta,
        argValues: [storagePath, orderId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantGetOrderConstMeta => const TaskConstMeta(
    debugName: "get_order",
    argNames: ["storagePath", "orderId"],
  );

  @override
  Future<List<PaymentOrderBridge>> crateApiMerchantGetPendingOrders({
    required String storagePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_payment_order_bridge,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantGetPendingOrdersConstMeta,
        argValues: [storagePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantGetPendingOrdersConstMeta =>
      const TaskConstMeta(
        debugName: "get_pending_orders",
        argNames: ["storagePath"],
      );

  @override
  Future<String> crateApiMerchantInitializeMbMerchant({
    required String storagePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantInitializeMbMerchantConstMeta,
        argValues: [storagePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantInitializeMbMerchantConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_mb_merchant",
        argNames: ["storagePath"],
      );

  @override
  Future<DidInfo> crateApiMerchantInitializeMerchant({
    required String storagePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_did_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantInitializeMerchantConstMeta,
        argValues: [storagePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantInitializeMerchantConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_merchant",
        argNames: ["storagePath"],
      );

  @override
  Future<DidInfo> crateApiMerchantDidcommInitializeMerchantComm({
    required String storagePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_did_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommInitializeMerchantCommConstMeta,
        argValues: [storagePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommInitializeMerchantCommConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_merchant_comm",
        argNames: ["storagePath"],
      );

  @override
  Future<List<PaymentOrderBridge>> crateApiMerchantListOrders({
    required String storagePath,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_payment_order_bridge,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantListOrdersConstMeta,
        argValues: [storagePath, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantListOrdersConstMeta => const TaskConstMeta(
    debugName: "list_orders",
    argNames: ["storagePath", "limit"],
  );

  @override
  Future<OobInvitationData> crateApiMerchantDidcommParseOobInvitation({
    required String invitationUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(invitationUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_oob_invitation_data,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommParseOobInvitationConstMeta,
        argValues: [invitationUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommParseOobInvitationConstMeta =>
      const TaskConstMeta(
        debugName: "parse_oob_invitation",
        argNames: ["invitationUrl"],
      );

  @override
  Future<List<DidcommMessage>> crateApiMerchantDidcommPullMessages({
    required String mediatorUrl,
    required String token,
    String? afterId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mediatorUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_opt_String(afterId, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_didcomm_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommPullMessagesConstMeta,
        argValues: [mediatorUrl, token, afterId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommPullMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "pull_messages",
        argNames: ["mediatorUrl", "token", "afterId", "limit"],
      );

  @override
  Future<List<AuditEntryBridge>> crateApiMerchantRecentAudit({
    required String storagePath,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_audit_entry_bridge,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantRecentAuditConstMeta,
        argValues: [storagePath, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantRecentAuditConstMeta =>
      const TaskConstMeta(
        debugName: "recent_audit",
        argNames: ["storagePath", "limit"],
      );

  @override
  Future<void> crateApiMerchantDidcommRegisterDeviceToken({
    required String mediatorUrl,
    required String authToken,
    required String fcmToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mediatorUrl, serializer);
          sse_encode_String(authToken, serializer);
          sse_encode_String(fcmToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommRegisterDeviceTokenConstMeta,
        argValues: [mediatorUrl, authToken, fcmToken],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommRegisterDeviceTokenConstMeta =>
      const TaskConstMeta(
        debugName: "register_device_token",
        argNames: ["mediatorUrl", "authToken", "fcmToken"],
      );

  @override
  Future<void> crateApiMerchantDidcommSendConnectionRequest({
    required String storagePath,
    required String mcpDid,
    required String mcpDidDocJson,
    required String mediatorWsUrl,
    required String pushChannel,
    String? fcmToken,
    String? appMediatorWsUrl,
    String? appMediatorHttpUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          sse_encode_String(mcpDid, serializer);
          sse_encode_String(mcpDidDocJson, serializer);
          sse_encode_String(mediatorWsUrl, serializer);
          sse_encode_String(pushChannel, serializer);
          sse_encode_opt_String(fcmToken, serializer);
          sse_encode_opt_String(appMediatorWsUrl, serializer);
          sse_encode_opt_String(appMediatorHttpUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommSendConnectionRequestConstMeta,
        argValues: [
          storagePath,
          mcpDid,
          mcpDidDocJson,
          mediatorWsUrl,
          pushChannel,
          fcmToken,
          appMediatorWsUrl,
          appMediatorHttpUrl,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommSendConnectionRequestConstMeta =>
      const TaskConstMeta(
        debugName: "send_connection_request",
        argNames: [
          "storagePath",
          "mcpDid",
          "mcpDidDocJson",
          "mediatorWsUrl",
          "pushChannel",
          "fcmToken",
          "appMediatorWsUrl",
          "appMediatorHttpUrl",
        ],
      );

  @override
  Future<void> crateApiMerchantDidcommSendCreateChannelRequest({
    required String storagePath,
    required String mcpDid,
    required String hubEndpoint,
    required String providerPubkey,
    required String tokenMint,
    required BigInt deposit,
    required int treeDepth,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          sse_encode_String(mcpDid, serializer);
          sse_encode_String(hubEndpoint, serializer);
          sse_encode_String(providerPubkey, serializer);
          sse_encode_String(tokenMint, serializer);
          sse_encode_u_64(deposit, serializer);
          sse_encode_u_32(treeDepth, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommSendCreateChannelRequestConstMeta,
        argValues: [
          storagePath,
          mcpDid,
          hubEndpoint,
          providerPubkey,
          tokenMint,
          deposit,
          treeDepth,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommSendCreateChannelRequestConstMeta =>
      const TaskConstMeta(
        debugName: "send_create_channel_request",
        argNames: [
          "storagePath",
          "mcpDid",
          "hubEndpoint",
          "providerPubkey",
          "tokenMint",
          "deposit",
          "treeDepth",
        ],
      );

  @override
  Future<void> crateApiMerchantDidcommSendMediatorUpdate({
    required String storagePath,
    required String peerDid,
    required String peerDidDocJson,
    required String mcpMediatorHttpUrl,
    required String mediatorHttpUrl,
    required String mediatorWsUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          sse_encode_String(peerDid, serializer);
          sse_encode_String(peerDidDocJson, serializer);
          sse_encode_String(mcpMediatorHttpUrl, serializer);
          sse_encode_String(mediatorHttpUrl, serializer);
          sse_encode_String(mediatorWsUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommSendMediatorUpdateConstMeta,
        argValues: [
          storagePath,
          peerDid,
          peerDidDocJson,
          mcpMediatorHttpUrl,
          mediatorHttpUrl,
          mediatorWsUrl,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommSendMediatorUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "send_mediator_update",
        argNames: [
          "storagePath",
          "peerDid",
          "peerDidDocJson",
          "mcpMediatorHttpUrl",
          "mediatorHttpUrl",
          "mediatorWsUrl",
        ],
      );

  @override
  Future<String> crateApiMerchantDidcommSignNonce({
    required String storagePath,
    required String nonce,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storagePath, serializer);
          sse_encode_String(nonce, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommSignNonceConstMeta,
        argValues: [storagePath, nonce],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommSignNonceConstMeta =>
      const TaskConstMeta(
        debugName: "sign_nonce",
        argNames: ["storagePath", "nonce"],
      );

  @override
  Future<bool> crateApiMerchantDidcommVerifyDidSignature({
    required String did,
    required String message,
    required String signatureB64,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(did, serializer);
          sse_encode_String(message, serializer);
          sse_encode_String(signatureB64, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMerchantDidcommVerifyDidSignatureConstMeta,
        argValues: [did, message, signatureB64],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMerchantDidcommVerifyDidSignatureConstMeta =>
      const TaskConstMeta(
        debugName: "verify_did_signature",
        argNames: ["did", "message", "signatureB64"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AuditEntryBridge dco_decode_audit_entry_bridge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AuditEntryBridge(
      timestamp: dco_decode_i_64(arr[0]),
      eventType: dco_decode_String(arr[1]),
      orderId: dco_decode_opt_String(arr[2]),
      amount: dco_decode_opt_box_autoadd_u_64(arr[3]),
      detail: dco_decode_String(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  PaymentOrderBridge dco_decode_box_autoadd_payment_order_bridge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_payment_order_bridge(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  DecryptedMessage dco_decode_decrypted_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return DecryptedMessage(
      msgType: dco_decode_String(arr[0]),
      fromDid: dco_decode_opt_String(arr[1]),
      paymentId: dco_decode_opt_String(arr[2]),
      orderId: dco_decode_opt_String(arr[3]),
      amount: dco_decode_opt_box_autoadd_u_64(arr[4]),
      description: dco_decode_opt_String(arr[5]),
      authorized: dco_decode_opt_box_autoadd_bool(arr[6]),
      channelId: dco_decode_opt_String(arr[7]),
      leafIndex: dco_decode_opt_box_autoadd_u_32(arr[8]),
      sequence: dco_decode_opt_box_autoadd_u_64(arr[9]),
      rawBody: dco_decode_String(arr[10]),
      tokenMint: dco_decode_opt_String(arr[11]),
    );
  }

  @protected
  DidInfo dco_decode_did_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DidInfo(
      did: dco_decode_String(arr[0]),
      didDocJson: dco_decode_String(arr[1]),
    );
  }

  @protected
  DidcommMessage dco_decode_didcomm_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DidcommMessage(
      msgId: dco_decode_String(arr[0]),
      jweEnvelope: dco_decode_String(arr[1]),
      createdAt: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  HubInfo dco_decode_hub_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return HubInfo(
      hubId: dco_decode_String(arr[0]),
      hubDid: dco_decode_String(arr[1]),
      endpointUrl: dco_decode_String(arr[2]),
      name: dco_decode_String(arr[3]),
      description: dco_decode_String(arr[4]),
      status: dco_decode_String(arr[5]),
      feeRateBps: dco_decode_u_16(arr[6]),
      availableLiquidity: dco_decode_u_64(arr[7]),
      onlineRate: dco_decode_u_16(arr[8]),
      successRate: dco_decode_u_16(arr[9]),
      avgLatencyMs: dco_decode_u_32(arr[10]),
      activeChannels: dco_decode_u_32(arr[11]),
      supportedTokens: dco_decode_list_String(arr[12]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AuditEntryBridge> dco_decode_list_audit_entry_bridge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audit_entry_bridge).toList();
  }

  @protected
  List<DidcommMessage> dco_decode_list_didcomm_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_didcomm_message).toList();
  }

  @protected
  List<HubInfo> dco_decode_list_hub_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_hub_info).toList();
  }

  @protected
  List<PaymentOrderBridge> dco_decode_list_payment_order_bridge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_payment_order_bridge).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  OobInvitationData dco_decode_oob_invitation_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return OobInvitationData(
      mcpDid: dco_decode_String(arr[0]),
      didDocJson: dco_decode_String(arr[1]),
      mediatorWsUrl: dco_decode_String(arr[2]),
      label: dco_decode_String(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  PaymentOrderBridge? dco_decode_opt_box_autoadd_payment_order_bridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_payment_order_bridge(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  PaymentOrderBridge dco_decode_payment_order_bridge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return PaymentOrderBridge(
      orderId: dco_decode_String(arr[0]),
      merchantDid: dco_decode_String(arr[1]),
      amount: dco_decode_u_64(arr[2]),
      description: dco_decode_String(arr[3]),
      hubEndpoint: dco_decode_String(arr[4]),
      status: dco_decode_String(arr[5]),
      createdAt: dco_decode_i_64(arr[6]),
      confirmedAt: dco_decode_opt_box_autoadd_i_64(arr[7]),
      channelId: dco_decode_opt_String(arr[8]),
      leafIndex: dco_decode_opt_box_autoadd_u_32(arr[9]),
      sequence: dco_decode_opt_box_autoadd_u_64(arr[10]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AuditEntryBridge sse_decode_audit_entry_bridge(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_eventType = sse_decode_String(deserializer);
    var var_orderId = sse_decode_opt_String(deserializer);
    var var_amount = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return AuditEntryBridge(
      timestamp: var_timestamp,
      eventType: var_eventType,
      orderId: var_orderId,
      amount: var_amount,
      detail: var_detail,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  PaymentOrderBridge sse_decode_box_autoadd_payment_order_bridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_payment_order_bridge(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  DecryptedMessage sse_decode_decrypted_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_msgType = sse_decode_String(deserializer);
    var var_fromDid = sse_decode_opt_String(deserializer);
    var var_paymentId = sse_decode_opt_String(deserializer);
    var var_orderId = sse_decode_opt_String(deserializer);
    var var_amount = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_authorized = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_channelId = sse_decode_opt_String(deserializer);
    var var_leafIndex = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_sequence = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_rawBody = sse_decode_String(deserializer);
    var var_tokenMint = sse_decode_opt_String(deserializer);
    return DecryptedMessage(
      msgType: var_msgType,
      fromDid: var_fromDid,
      paymentId: var_paymentId,
      orderId: var_orderId,
      amount: var_amount,
      description: var_description,
      authorized: var_authorized,
      channelId: var_channelId,
      leafIndex: var_leafIndex,
      sequence: var_sequence,
      rawBody: var_rawBody,
      tokenMint: var_tokenMint,
    );
  }

  @protected
  DidInfo sse_decode_did_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_did = sse_decode_String(deserializer);
    var var_didDocJson = sse_decode_String(deserializer);
    return DidInfo(did: var_did, didDocJson: var_didDocJson);
  }

  @protected
  DidcommMessage sse_decode_didcomm_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_msgId = sse_decode_String(deserializer);
    var var_jweEnvelope = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    return DidcommMessage(
      msgId: var_msgId,
      jweEnvelope: var_jweEnvelope,
      createdAt: var_createdAt,
    );
  }

  @protected
  HubInfo sse_decode_hub_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hubId = sse_decode_String(deserializer);
    var var_hubDid = sse_decode_String(deserializer);
    var var_endpointUrl = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_feeRateBps = sse_decode_u_16(deserializer);
    var var_availableLiquidity = sse_decode_u_64(deserializer);
    var var_onlineRate = sse_decode_u_16(deserializer);
    var var_successRate = sse_decode_u_16(deserializer);
    var var_avgLatencyMs = sse_decode_u_32(deserializer);
    var var_activeChannels = sse_decode_u_32(deserializer);
    var var_supportedTokens = sse_decode_list_String(deserializer);
    return HubInfo(
      hubId: var_hubId,
      hubDid: var_hubDid,
      endpointUrl: var_endpointUrl,
      name: var_name,
      description: var_description,
      status: var_status,
      feeRateBps: var_feeRateBps,
      availableLiquidity: var_availableLiquidity,
      onlineRate: var_onlineRate,
      successRate: var_successRate,
      avgLatencyMs: var_avgLatencyMs,
      activeChannels: var_activeChannels,
      supportedTokens: var_supportedTokens,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AuditEntryBridge> sse_decode_list_audit_entry_bridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AuditEntryBridge>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audit_entry_bridge(deserializer));
    }
    return ans_;
  }

  @protected
  List<DidcommMessage> sse_decode_list_didcomm_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DidcommMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_didcomm_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<HubInfo> sse_decode_list_hub_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HubInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_hub_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<PaymentOrderBridge> sse_decode_list_payment_order_bridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PaymentOrderBridge>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_payment_order_bridge(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  OobInvitationData sse_decode_oob_invitation_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mcpDid = sse_decode_String(deserializer);
    var var_didDocJson = sse_decode_String(deserializer);
    var var_mediatorWsUrl = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    return OobInvitationData(
      mcpDid: var_mcpDid,
      didDocJson: var_didDocJson,
      mediatorWsUrl: var_mediatorWsUrl,
      label: var_label,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PaymentOrderBridge? sse_decode_opt_box_autoadd_payment_order_bridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_payment_order_bridge(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PaymentOrderBridge sse_decode_payment_order_bridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_orderId = sse_decode_String(deserializer);
    var var_merchantDid = sse_decode_String(deserializer);
    var var_amount = sse_decode_u_64(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_hubEndpoint = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_confirmedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_channelId = sse_decode_opt_String(deserializer);
    var var_leafIndex = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_sequence = sse_decode_opt_box_autoadd_u_64(deserializer);
    return PaymentOrderBridge(
      orderId: var_orderId,
      merchantDid: var_merchantDid,
      amount: var_amount,
      description: var_description,
      hubEndpoint: var_hubEndpoint,
      status: var_status,
      createdAt: var_createdAt,
      confirmedAt: var_confirmedAt,
      channelId: var_channelId,
      leafIndex: var_leafIndex,
      sequence: var_sequence,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audit_entry_bridge(
    AuditEntryBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_String(self.eventType, serializer);
    sse_encode_opt_String(self.orderId, serializer);
    sse_encode_opt_box_autoadd_u_64(self.amount, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_payment_order_bridge(
    PaymentOrderBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_payment_order_bridge(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_decrypted_message(
    DecryptedMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.msgType, serializer);
    sse_encode_opt_String(self.fromDid, serializer);
    sse_encode_opt_String(self.paymentId, serializer);
    sse_encode_opt_String(self.orderId, serializer);
    sse_encode_opt_box_autoadd_u_64(self.amount, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_box_autoadd_bool(self.authorized, serializer);
    sse_encode_opt_String(self.channelId, serializer);
    sse_encode_opt_box_autoadd_u_32(self.leafIndex, serializer);
    sse_encode_opt_box_autoadd_u_64(self.sequence, serializer);
    sse_encode_String(self.rawBody, serializer);
    sse_encode_opt_String(self.tokenMint, serializer);
  }

  @protected
  void sse_encode_did_info(DidInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.did, serializer);
    sse_encode_String(self.didDocJson, serializer);
  }

  @protected
  void sse_encode_didcomm_message(
    DidcommMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.msgId, serializer);
    sse_encode_String(self.jweEnvelope, serializer);
    sse_encode_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_hub_info(HubInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.hubId, serializer);
    sse_encode_String(self.hubDid, serializer);
    sse_encode_String(self.endpointUrl, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_u_16(self.feeRateBps, serializer);
    sse_encode_u_64(self.availableLiquidity, serializer);
    sse_encode_u_16(self.onlineRate, serializer);
    sse_encode_u_16(self.successRate, serializer);
    sse_encode_u_32(self.avgLatencyMs, serializer);
    sse_encode_u_32(self.activeChannels, serializer);
    sse_encode_list_String(self.supportedTokens, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_audit_entry_bridge(
    List<AuditEntryBridge> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audit_entry_bridge(item, serializer);
    }
  }

  @protected
  void sse_encode_list_didcomm_message(
    List<DidcommMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_didcomm_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_hub_info(List<HubInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_hub_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_payment_order_bridge(
    List<PaymentOrderBridge> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_payment_order_bridge(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_oob_invitation_data(
    OobInvitationData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mcpDid, serializer);
    sse_encode_String(self.didDocJson, serializer);
    sse_encode_String(self.mediatorWsUrl, serializer);
    sse_encode_String(self.label, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_payment_order_bridge(
    PaymentOrderBridge? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_payment_order_bridge(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_payment_order_bridge(
    PaymentOrderBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.orderId, serializer);
    sse_encode_String(self.merchantDid, serializer);
    sse_encode_u_64(self.amount, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.hubEndpoint, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.confirmedAt, serializer);
    sse_encode_opt_String(self.channelId, serializer);
    sse_encode_opt_box_autoadd_u_32(self.leafIndex, serializer);
    sse_encode_opt_box_autoadd_u_64(self.sequence, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
