// Copyright (c) 2026 zouyc zouyccq@gmail.com.
// All rights reserved.
//
// Licensed under the Business Source License 1.1 (BSL 1.1).
// You may not use this file except in compliance with the License.
//
// Change Date: 2031-01-01
// On the Change Date, or the fourth anniversary of the first publicly available
// distribution of the code under the BSL, whichever comes first, the code
// automatically becomes available under the Apache License 2.0.

// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `audit_tree`, `get_keypair_from_storage`, `keypair_tree`, `open_db_from_global`, `open_db`, `orders_tree`, `parse_channel_id`, `to_bridge`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AuditEntry`, `OrderStatus`, `PaymentOrder`, `PaymentQrData`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Initialize merchant identity - generates or loads DID from storage.
Future<DidInfo> initializeMerchant({required String storagePath}) => RustLib
    .instance
    .api
    .crateApiMerchantInitializeMerchant(storagePath: storagePath);

/// Get the merchant DID from storage.
Future<String> getMerchantDid({required String storagePath}) => RustLib
    .instance
    .api
    .crateApiMerchantGetMerchantDid(storagePath: storagePath);

/// Generate a merchant keypair, returns base58-encoded public key.
Future<String> generateMerchantKeypair({required String storagePath}) => RustLib
    .instance
    .api
    .crateApiMerchantGenerateMerchantKeypair(storagePath: storagePath);

/// Get the stored merchant public key as base58.
Future<String> getMerchantPubkey({required String storagePath}) => RustLib
    .instance
    .api
    .crateApiMerchantGetMerchantPubkey(storagePath: storagePath);

/// Generate a payment QR string and create an order.
/// Format: `ignite://pay?d=<base64url(json)>`
Future<String> generatePaymentQr({
  required String merchantDid,
  required BigInt amount,
  required String description,
  required String hubEndpoint,
  required String merchantMbPubkey,
}) => RustLib.instance.api.crateApiMerchantGeneratePaymentQr(
  merchantDid: merchantDid,
  amount: amount,
  description: description,
  hubEndpoint: hubEndpoint,
  merchantMbPubkey: merchantMbPubkey,
);

/// Generate an ASCII QR code for debugging.
Future<String> generateQrAscii({required String qrText}) =>
    RustLib.instance.api.crateApiMerchantGenerateQrAscii(qrText: qrText);

/// List recent payment orders.
Future<List<PaymentOrderBridge>> listOrders({
  required String storagePath,
  required int limit,
}) => RustLib.instance.api.crateApiMerchantListOrders(
  storagePath: storagePath,
  limit: limit,
);

/// Get a single payment order by ID.
Future<PaymentOrderBridge?> getOrder({
  required String storagePath,
  required String orderId,
}) => RustLib.instance.api.crateApiMerchantGetOrder(
  storagePath: storagePath,
  orderId: orderId,
);

/// Confirm a payment order with channel metadata.
Future<void> confirmOrder({
  required String storagePath,
  required String orderId,
  required String channelId,
  required int leafIndex,
  required BigInt sequence,
}) => RustLib.instance.api.crateApiMerchantConfirmOrder(
  storagePath: storagePath,
  orderId: orderId,
  channelId: channelId,
  leafIndex: leafIndex,
  sequence: sequence,
);

/// Get all pending (unconfirmed) orders.
Future<List<PaymentOrderBridge>> getPendingOrders({
  required String storagePath,
}) => RustLib.instance.api.crateApiMerchantGetPendingOrders(
  storagePath: storagePath,
);

/// List all state channel IDs.
Future<List<String>> merchantListChannels({required String storagePath}) =>
    RustLib.instance.api.crateApiMerchantMerchantListChannels(
      storagePath: storagePath,
    );

/// Get channel status.
Future<ChannelStatusBridge> merchantGetChannelStatus({
  required String storagePath,
  required String channelId,
}) => RustLib.instance.api.crateApiMerchantMerchantGetChannelStatus(
  storagePath: storagePath,
  channelId: channelId,
);

/// Cooperative close a channel.
Future<String> merchantCloseChannel({
  required String storagePath,
  required String hubEndpoint,
  required String channelId,
}) => RustLib.instance.api.crateApiMerchantMerchantCloseChannel(
  storagePath: storagePath,
  hubEndpoint: hubEndpoint,
  channelId: channelId,
);

/// Claim a leaf during settlement.
Future<String> merchantClaimLeaf({
  required String storagePath,
  required String hubEndpoint,
  required String channelId,
  required int leafIndex,
  required BigInt amount,
}) => RustLib.instance.api.crateApiMerchantMerchantClaimLeaf(
  storagePath: storagePath,
  hubEndpoint: hubEndpoint,
  channelId: channelId,
  leafIndex: leafIndex,
  amount: amount,
);

/// Finalize settlement.
Future<String> merchantFinalize({
  required String storagePath,
  required String hubEndpoint,
  required String channelId,
}) => RustLib.instance.api.crateApiMerchantMerchantFinalize(
  storagePath: storagePath,
  hubEndpoint: hubEndpoint,
  channelId: channelId,
);

/// Append an audit log entry.
Future<void> appendAudit({
  required String storagePath,
  required String eventType,
  String? orderId,
  BigInt? amount,
  required String detail,
}) => RustLib.instance.api.crateApiMerchantAppendAudit(
  storagePath: storagePath,
  eventType: eventType,
  orderId: orderId,
  amount: amount,
  detail: detail,
);

/// Get recent audit entries.
Future<List<AuditEntryBridge>> recentAudit({
  required String storagePath,
  required int limit,
}) => RustLib.instance.api.crateApiMerchantRecentAudit(
  storagePath: storagePath,
  limit: limit,
);

class AuditEntryBridge {
  final PlatformInt64 timestamp;
  final String eventType;
  final String? orderId;
  final BigInt? amount;
  final String detail;

  const AuditEntryBridge({
    required this.timestamp,
    required this.eventType,
    this.orderId,
    this.amount,
    required this.detail,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^
      eventType.hashCode ^
      orderId.hashCode ^
      amount.hashCode ^
      detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditEntryBridge &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          eventType == other.eventType &&
          orderId == other.orderId &&
          amount == other.amount &&
          detail == other.detail;
}

class ChannelStatusBridge {
  final String channelId;
  final String status;
  final BigInt sequence;
  final int leafCount;
  final BigInt providerBalance;
  final BigInt totalDeposited;

  const ChannelStatusBridge({
    required this.channelId,
    required this.status,
    required this.sequence,
    required this.leafCount,
    required this.providerBalance,
    required this.totalDeposited,
  });

  @override
  int get hashCode =>
      channelId.hashCode ^
      status.hashCode ^
      sequence.hashCode ^
      leafCount.hashCode ^
      providerBalance.hashCode ^
      totalDeposited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelStatusBridge &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          status == other.status &&
          sequence == other.sequence &&
          leafCount == other.leafCount &&
          providerBalance == other.providerBalance &&
          totalDeposited == other.totalDeposited;
}

class DidInfo {
  final String did;
  final String didDocJson;

  const DidInfo({required this.did, required this.didDocJson});

  @override
  int get hashCode => did.hashCode ^ didDocJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DidInfo &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          didDocJson == other.didDocJson;
}

/// Initialize or load MB merchant keypair, return base58 pubkey.
Future<String> initializeMbMerchant({required String storagePath}) => RustLib
    .instance
    .api
    .crateApiMerchantInitializeMbMerchant(storagePath: storagePath);

/// Get the MB merchant pubkey from storage.
Future<String> getMbMerchantPubkey({required String storagePath}) => RustLib
    .instance
    .api
    .crateApiMerchantGetMbMerchantPubkey(storagePath: storagePath);

class PaymentOrderBridge {
  final String orderId;
  final String merchantDid;
  final BigInt amount;
  final String description;
  final String hubEndpoint;
  final String status;
  final PlatformInt64 createdAt;
  final PlatformInt64? confirmedAt;
  final String? channelId;
  final int? leafIndex;
  final BigInt? sequence;

  const PaymentOrderBridge({
    required this.orderId,
    required this.merchantDid,
    required this.amount,
    required this.description,
    required this.hubEndpoint,
    required this.status,
    required this.createdAt,
    this.confirmedAt,
    this.channelId,
    this.leafIndex,
    this.sequence,
  });

  @override
  int get hashCode =>
      orderId.hashCode ^
      merchantDid.hashCode ^
      amount.hashCode ^
      description.hashCode ^
      hubEndpoint.hashCode ^
      status.hashCode ^
      createdAt.hashCode ^
      confirmedAt.hashCode ^
      channelId.hashCode ^
      leafIndex.hashCode ^
      sequence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentOrderBridge &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId &&
          merchantDid == other.merchantDid &&
          amount == other.amount &&
          description == other.description &&
          hubEndpoint == other.hubEndpoint &&
          status == other.status &&
          createdAt == other.createdAt &&
          confirmedAt == other.confirmedAt &&
          channelId == other.channelId &&
          leafIndex == other.leafIndex &&
          sequence == other.sequence;
}
