// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'merchant.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Initialize the DIDComm communication identity.
/// Uses ignite_pay_core's identity module (same DID format as user app).
/// This DID is independent from the state channel DID in merchant.rs.
Future<DidInfo> initializeMerchantComm({required String storagePath}) => RustLib
    .instance
    .api
    .crateApiMerchantDidcommInitializeMerchantComm(storagePath: storagePath);

/// Connect to the DIDComm mediator via WebSocket.
Future<void> connectMediator({
  required String storagePath,
  required String wsUrl,
}) => RustLib.instance.api.crateApiMerchantDidcommConnectMediator(
  storagePath: storagePath,
  wsUrl: wsUrl,
);

/// Disconnect from the mediator.
Future<void> disconnectMediator() =>
    RustLib.instance.api.crateApiMerchantDidcommDisconnectMediator();

/// Authenticate with the mediator via challenge-response.
/// Signs the nonce with the actual Ed25519 signing key from identity storage.
Future<String> authenticateWithMediator({
  required String mediatorUrl,
  required String storagePath,
  required String did,
}) => RustLib.instance.api.crateApiMerchantDidcommAuthenticateWithMediator(
  mediatorUrl: mediatorUrl,
  storagePath: storagePath,
  did: did,
);

/// Pull DIDComm message envelopes from the mediator via HTTPS.
Future<List<DidcommMessage>> pullMessages({
  required String mediatorUrl,
  required String token,
  String? afterId,
  required int limit,
}) => RustLib.instance.api.crateApiMerchantDidcommPullMessages(
  mediatorUrl: mediatorUrl,
  token: token,
  afterId: afterId,
  limit: limit,
);

/// Decrypt a JWE message using the DIDComm identity agent.
/// Extracts merchant-relevant fields: payment-auth-response, channel-payment-confirm.
Future<DecryptedMessage> decryptMessage({
  required String storagePath,
  required String jwe,
}) => RustLib.instance.api.crateApiMerchantDidcommDecryptMessage(
  storagePath: storagePath,
  jwe: jwe,
);

/// Sign a nonce string with the merchant's Ed25519 signing key.
/// Returns the base64-no-pad encoded signature.
Future<String> signNonce({
  required String storagePath,
  required String nonce,
}) => RustLib.instance.api.crateApiMerchantDidcommSignNonce(
  storagePath: storagePath,
  nonce: nonce,
);

/// Verify an Ed25519 signature from a DID.
/// Returns true if the signature is valid for the given message and DID.
Future<bool> verifyDidSignature({
  required String did,
  required String message,
  required String signatureB64,
}) => RustLib.instance.api.crateApiMerchantDidcommVerifyDidSignature(
  did: did,
  message: message,
  signatureB64: signatureB64,
);

/// Register an FCM device token with the mediator.
Future<void> registerDeviceToken({
  required String mediatorUrl,
  required String authToken,
  required String fcmToken,
}) => RustLib.instance.api.crateApiMerchantDidcommRegisterDeviceToken(
  mediatorUrl: mediatorUrl,
  authToken: authToken,
  fcmToken: fcmToken,
);

/// Fetch the list of available hubs from the hub registry.
Future<List<HubInfo>> fetchHubList({required String registryUrl}) => RustLib
    .instance
    .api
    .crateApiMerchantDidcommFetchHubList(registryUrl: registryUrl);

/// Parse an OOB invitation URL (from QR code scan).
/// Expected format: didcomm://?_oob=<base64url-encoded JSON>
Future<OobInvitationData> parseOobInvitation({required String invitationUrl}) =>
    RustLib.instance.api.crateApiMerchantDidcommParseOobInvitation(
      invitationUrl: invitationUrl,
    );

/// Send a connection request to the MCP after parsing the QR invitation.
/// Includes the merchant app's mediator HTTP URL so the MCP can forward messages back.
Future<void> sendConnectionRequest({
  required String storagePath,
  required String mcpDid,
  required String mcpDidDocJson,
  required String mediatorWsUrl,
  required String pushChannel,
  String? fcmToken,
  String? appMediatorWsUrl,
  String? appMediatorHttpUrl,
}) => RustLib.instance.api.crateApiMerchantDidcommSendConnectionRequest(
  storagePath: storagePath,
  mcpDid: mcpDid,
  mcpDidDocJson: mcpDidDocJson,
  mediatorWsUrl: mediatorWsUrl,
  pushChannel: pushChannel,
  fcmToken: fcmToken,
  appMediatorWsUrl: appMediatorWsUrl,
  appMediatorHttpUrl: appMediatorHttpUrl,
);

/// Send a create-channel request to the merchant MCP server via DIDComm.
Future<void> sendCreateChannelRequest({
  required String storagePath,
  required String mcpDid,
  required String hubEndpoint,
  required String providerPubkey,
  required String tokenMint,
  required BigInt deposit,
  required int treeDepth,
}) => RustLib.instance.api.crateApiMerchantDidcommSendCreateChannelRequest(
  storagePath: storagePath,
  mcpDid: mcpDid,
  hubEndpoint: hubEndpoint,
  providerPubkey: providerPubkey,
  tokenMint: tokenMint,
  deposit: deposit,
  treeDepth: treeDepth,
);

class DecryptedMessage {
  final String msgType;
  final String? paymentId;
  final String? orderId;
  final BigInt? amount;
  final String? description;
  final bool? authorized;
  final String? channelId;
  final int? leafIndex;
  final BigInt? sequence;
  final String rawBody;

  const DecryptedMessage({
    required this.msgType,
    this.paymentId,
    this.orderId,
    this.amount,
    this.description,
    this.authorized,
    this.channelId,
    this.leafIndex,
    this.sequence,
    required this.rawBody,
  });

  @override
  int get hashCode =>
      msgType.hashCode ^
      paymentId.hashCode ^
      orderId.hashCode ^
      amount.hashCode ^
      description.hashCode ^
      authorized.hashCode ^
      channelId.hashCode ^
      leafIndex.hashCode ^
      sequence.hashCode ^
      rawBody.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecryptedMessage &&
          runtimeType == other.runtimeType &&
          msgType == other.msgType &&
          paymentId == other.paymentId &&
          orderId == other.orderId &&
          amount == other.amount &&
          description == other.description &&
          authorized == other.authorized &&
          channelId == other.channelId &&
          leafIndex == other.leafIndex &&
          sequence == other.sequence &&
          rawBody == other.rawBody;
}

class DidcommMessage {
  final String msgId;
  final String jweEnvelope;
  final PlatformInt64 createdAt;

  const DidcommMessage({
    required this.msgId,
    required this.jweEnvelope,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      msgId.hashCode ^ jweEnvelope.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DidcommMessage &&
          runtimeType == other.runtimeType &&
          msgId == other.msgId &&
          jweEnvelope == other.jweEnvelope &&
          createdAt == other.createdAt;
}

/// Hub info from the registry.
class HubInfo {
  final String hubId;
  final String hubDid;
  final String endpointUrl;
  final String name;
  final String description;
  final String status;
  final int feeRateBps;
  final BigInt availableLiquidity;
  final int onlineRate;
  final int successRate;
  final int avgLatencyMs;
  final int activeChannels;
  final List<String> supportedTokens;

  const HubInfo({
    required this.hubId,
    required this.hubDid,
    required this.endpointUrl,
    required this.name,
    required this.description,
    required this.status,
    required this.feeRateBps,
    required this.availableLiquidity,
    required this.onlineRate,
    required this.successRate,
    required this.avgLatencyMs,
    required this.activeChannels,
    required this.supportedTokens,
  });

  @override
  int get hashCode =>
      hubId.hashCode ^
      hubDid.hashCode ^
      endpointUrl.hashCode ^
      name.hashCode ^
      description.hashCode ^
      status.hashCode ^
      feeRateBps.hashCode ^
      availableLiquidity.hashCode ^
      onlineRate.hashCode ^
      successRate.hashCode ^
      avgLatencyMs.hashCode ^
      activeChannels.hashCode ^
      supportedTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HubInfo &&
          runtimeType == other.runtimeType &&
          hubId == other.hubId &&
          hubDid == other.hubDid &&
          endpointUrl == other.endpointUrl &&
          name == other.name &&
          description == other.description &&
          status == other.status &&
          feeRateBps == other.feeRateBps &&
          availableLiquidity == other.availableLiquidity &&
          onlineRate == other.onlineRate &&
          successRate == other.successRate &&
          avgLatencyMs == other.avgLatencyMs &&
          activeChannels == other.activeChannels &&
          supportedTokens == other.supportedTokens;
}

/// Parsed OOB invitation data from a QR code scan.
class OobInvitationData {
  final String mcpDid;
  final String didDocJson;
  final String mediatorWsUrl;
  final String label;

  const OobInvitationData({
    required this.mcpDid,
    required this.didDocJson,
    required this.mediatorWsUrl,
    required this.label,
  });

  @override
  int get hashCode =>
      mcpDid.hashCode ^
      didDocJson.hashCode ^
      mediatorWsUrl.hashCode ^
      label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OobInvitationData &&
          runtimeType == other.runtimeType &&
          mcpDid == other.mcpDid &&
          didDocJson == other.didDocJson &&
          mediatorWsUrl == other.mediatorWsUrl &&
          label == other.label;
}
