// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuJyeHSEVeqlOswWQkZ66kMWqe-pDzxs4',
    appId: '1:389818499028:android:304546bf6fb12a40c76041',
    messagingSenderId: '389818499028',
    projectId: 'ignite-pay-d1217',
    storageBucket: 'ignite-pay-d1217.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpIdDEKabDBz1Pq3FoIr2krjV-BANP_QQ',
    appId: '1:389818499028:ios:02e512743acc97d2c76041',
    messagingSenderId: '389818499028',
    projectId: 'ignite-pay-d1217',
    storageBucket: 'ignite-pay-d1217.firebasestorage.app',
    iosBundleId: 'com.ignitepay.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0nPrUfZeGSTtdvyoKzy-vQ9vekbhqwtI',
    appId: '1:389818499028:web:604e5e921857d227c76041',
    messagingSenderId: '389818499028',
    projectId: 'ignite-pay-d1217',
    authDomain: 'ignite-pay-d1217.firebaseapp.com',
    storageBucket: 'ignite-pay-d1217.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpIdDEKabDBz1Pq3FoIr2krjV-BANP_QQ',
    appId: '1:389818499028:ios:02e512743acc97d2c76041',
    messagingSenderId: '389818499028',
    projectId: 'ignite-pay-d1217',
    storageBucket: 'ignite-pay-d1217.firebasestorage.app',
    iosBundleId: 'com.ignitepay.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0nPrUfZeGSTtdvyoKzy-vQ9vekbhqwtI',
    appId: '1:389818499028:web:5c18d3acf29975d6c76041',
    messagingSenderId: '389818499028',
    projectId: 'ignite-pay-d1217',
    authDomain: 'ignite-pay-d1217.firebaseapp.com',
    storageBucket: 'ignite-pay-d1217.firebasestorage.app',
  );

}